Repository prgrms-be-devcourse/springboot-board-jpa, pull requests merged in 2021-11, with the labels that each got.

#8 [1기-C] 박권규 - JPA 게시판 만들기
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/post.adoc
  src/docs/asciidoc/user.adoc
  src/main/java/com/devcourse/bbs/BbsApplication.java
  src/main/java/com/devcourse/bbs/controller/PostController.java
  src/main/java/com/devcourse/bbs/controller/UserController.java
  src/main/java/com/devcourse/bbs/controller/bind/ApiResponse.java
  src/main/java/com/devcourse/bbs/controller/bind/FieldErrorDetail.java
  src/main/java/com/devcourse/bbs/controller/bind/PostCreateRequest.java
  src/main/java/com/devcourse/bbs/controller/bind/PostUpdateRequest.java
  src/main/java/com/devcourse/bbs/controller/bind/UserCreateRequest.java
  src/main/java/com/devcourse/bbs/controller/bind/UserUpdateRequest.java
  src/main/java/com/devcourse/bbs/domain/DateRecordedEntity.java
  src/main/java/com/devcourse/bbs/domain/post/Post.java
  src/main/java/com/devcourse/bbs/domain/post/PostDTO.java
  src/main/java/com/devcourse/bbs/domain/user/User.java
  src/main/java/com/devcourse/bbs/domain/user/UserDTO.java
  src/main/java/com/devcourse/bbs/exception/ControllerExceptionHandler.java
  src/main/java/com/devcourse/bbs/repository/post/PostRepository.java
  src/main/java/com/devcourse/bbs/repository/user/UserRepository.java
  src/main/java/com/devcourse/bbs/service/post/BasicPostService.java
  src/main/java/com/devcourse/bbs/service/post/PostService.java
  src/main/java/com/devcourse/bbs/service/user/BasicUserService.java
  src/main/java/com/devcourse/bbs/service/user/UserService.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/devcourse/bbs/PostControllerTest.java
  src/test/java/com/devcourse/bbs/PostRepositoryTest.java
  src/test/java/com/devcourse/bbs/PostServiceTest.java
  src/test/java/com/devcourse/bbs/UserControllerTest.java
  src/test/java/com/devcourse/bbs/UserRepositoryTest.java
  src/test/java/com/devcourse/bbs/UserServiceTest.java
Labels: 과제 리뷰 요청, Team-Victory, 🔥 매운맛

#46 [1기-C 한재원] JPA 게시판 만들기
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  README.md
  board-backend/.gitignore
  board-backend/build.gradle
  board-backend/src/main/java/com/example/boardbackend/BoardBackendApplication.java
  board-backend/src/main/resources/schema.sql
  board-frontend/README.md
  board-frontend/package-lock.json
  board-frontend/package.json
  board-frontend/public/img/ms.png
  board-frontend/src/App.css
  board-frontend/src/App.js
  board-frontend/src/components/Menu.js
  board-frontend/src/views/Board.js
  board-frontend/src/views/Login.js
  board-frontend/src/views/Mypage.js
  board-frontend/src/views/Post.js
  board-frontend/src/views/Posting.js
  board-frontend/src/views/SignUp.js
  board-frontend/src/views/UpdatePost.js
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/example/boardbackend/BoardBackendApplication.java
  src/main/java/com/example/boardbackend/common/config/MvcConfiguration.java
  src/main/java/com/example/boardbackend/common/error/ErrorHandler.java
  src/main/java/com/example/boardbackend/common/error/exception/IllegalArgException.java
  src/main/java/com/example/boardbackend/common/error/exception/NotFoundException.java
  src/main/java/com/example/boardbackend/common/error/response/ErrorResponse.java
  src/main/java/com/example/boardbackend/common/error/response/NotValidResponse.java
  src/main/java/com/example/boardbackend/controller/PostController.java
  src/main/java/com/example/boardbackend/controller/SearchType.java
  src/main/java/com/example/boardbackend/controller/UserController.java
  src/main/java/com/example/boardbackend/domain/BaseEntity.java
  src/main/java/com/example/boardbackend/domain/Post.java
  src/main/java/com/example/boardbackend/domain/User.java
  src/main/java/com/example/boardbackend/domain/embeded/Email.java
  src/main/java/com/example/boardbackend/dto/PostDto.java
  src/main/java/com/example/boardbackend/dto/UserDto.java
  src/main/java/com/example/boardbackend/dto/request/LoginRequest.java
  src/main/java/com/example/boardbackend/dto/request/UpdatePostRequest.java
  src/main/java/com/example/boardbackend/dto/request/UpdateViewRequest.java
  src/main/java/com/example/boardbackend/dto/response/BoardResponse.java
  src/main/java/com/example/boardbackend/dto/response/UserIdResponse.java
  src/main/java/com/example/boardbackend/repository/PostRepository.java
  src/main/java/com/example/boardbackend/repository/UserRepository.java
  src/main/java/com/example/boardbackend/service/PostService.java
  src/main/java/com/example/boardbackend/service/UserService.java
  src/main/resources/application.yaml
  src/test/java/com/example/boardbackend/BoardBackendApplicationTests.java
  src/test/java/com/example/boardbackend/controller/PostControllerTest.java
  src/test/java/com/example/boardbackend/controller/UserControllerTest.java
  src/test/java/com/example/boardbackend/service/PostServiceTest.java
  src/test/java/com/example/boardbackend/service/UserServiceTest.java
Labels: 과제 리뷰 요청, Team-Amand

#15 [1기 - C] 함승훈 게시판 API 구현
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/docs/asciidoc/index.adoc
  src/main/java/com/example/springbootboard/SpringBootBoardApplication.java
  src/main/java/com/example/springbootboard/controller/PostApiController.java
  src/main/java/com/example/springbootboard/domain/BaseEntity.java
  src/main/java/com/example/springbootboard/domain/Hobby.java
  src/main/java/com/example/springbootboard/domain/Post.java
  src/main/java/com/example/springbootboard/domain/Title.java
  src/main/java/com/example/springbootboard/domain/User.java
  src/main/java/com/example/springbootboard/dto/PagePostDto.java
  src/main/java/com/example/springbootboard/dto/ResponseDto.java
  src/main/java/com/example/springbootboard/dto/UserDto.java
  src/main/java/com/example/springbootboard/dto/request/RequestCreatePost.java
  src/main/java/com/example/springbootboard/dto/request/RequestPagePost.java
  src/main/java/com/example/springbootboard/dto/request/RequestUpdatePost.java
  src/main/java/com/example/springbootboard/dto/response/PostDto.java
  src/main/java/com/example/springbootboard/error/ErrorResponse.java
  src/main/java/com/example/springbootboard/error/GlobalExceptionHandler.java
  src/main/java/com/example/springbootboard/error/exception/BusinessException.java
  src/main/java/com/example/springbootboard/error/exception/EntityNotFoundException.java
  src/main/java/com/example/springbootboard/error/exception/ErrorCode.java
  src/main/java/com/example/springbootboard/repository/PostRepository.java
  src/main/java/com/example/springbootboard/repository/UserRepository.java
  src/main/java/com/example/springbootboard/service/PostService.java
  src/main/resources/application.yml
  src/test/java/com/example/springbootboard/SpringBootBoardApplicationTests.java
  src/test/java/com/example/springbootboard/controller/PostApiControllerTest.java
  src/test/java/com/example/springbootboard/domain/PostTest.java
  src/test/java/com/example/springbootboard/domain/UserTest.java
  src/test/java/com/example/springbootboard/repository/PostRepositoryTest.java
  src/test/java/com/example/springbootboard/repository/UserRepositoryTest.java
  src/test/java/com/example/springbootboard/service/PostServiceTest.java
Labels: 과제 리뷰 요청, 피드백 요청, Team-Amand

#43 [1기-C] 한맹희 - JPA 게시판 API
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/docs/asciidoc/index.adoc
  src/main/java/com/maenguin/kdtbbs/KdtbbsApplication.java
  src/main/java/com/maenguin/kdtbbs/config/JpaAuditingConfiguration.java
  src/main/java/com/maenguin/kdtbbs/controller/InitDB.java
  src/main/java/com/maenguin/kdtbbs/controller/OptimisticLockTryer.java
  src/main/java/com/maenguin/kdtbbs/controller/PostRestController.java
  src/main/java/com/maenguin/kdtbbs/converter/BBSConverter.java
  src/main/java/com/maenguin/kdtbbs/domain/BaseEntity.java
  src/main/java/com/maenguin/kdtbbs/domain/Post.java
  src/main/java/com/maenguin/kdtbbs/domain/User.java
  src/main/java/com/maenguin/kdtbbs/dto/ApiResponse.java
  src/main/java/com/maenguin/kdtbbs/dto/PaginationDto.java
  src/main/java/com/maenguin/kdtbbs/dto/PostAddDto.java
  src/main/java/com/maenguin/kdtbbs/dto/PostAddResDto.java
  src/main/java/com/maenguin/kdtbbs/dto/PostDto.java
  src/main/java/com/maenguin/kdtbbs/dto/PostListDto.java
  src/main/java/com/maenguin/kdtbbs/dto/UserDto.java
  src/main/java/com/maenguin/kdtbbs/exception/BusinessException.java
  src/main/java/com/maenguin/kdtbbs/exception/ErrorCode.java
  src/main/java/com/maenguin/kdtbbs/exception/GlobalExceptionHandler.java
  src/main/java/com/maenguin/kdtbbs/exception/NotFoundException.java
  src/main/java/com/maenguin/kdtbbs/exception/PostNotFoundException.java
  src/main/java/com/maenguin/kdtbbs/exception/UserNotFoundException.java
  src/main/java/com/maenguin/kdtbbs/repository/PostRepository.java
  src/main/java/com/maenguin/kdtbbs/repository/UserRepository.java
  src/main/java/com/maenguin/kdtbbs/service/PostService.java
  src/main/resources/application.yml
  src/test/java/com/maenguin/kdtbbs/KdtbbsApplicationTests.java
  src/test/java/com/maenguin/kdtbbs/controller/PostDocumentationTest.java
  src/test/java/com/maenguin/kdtbbs/controller/PostRestControllerTest.java
  src/test/java/com/maenguin/kdtbbs/service/PostLockTest.java
  src/test/java/com/maenguin/kdtbbs/service/PostServiceTest.java
Labels: 과제 리뷰 요청, 🔥 매운맛, Team-Marco
