Repository prgrms-be-devcourse/springboot-board-jpa, pull requests merged in 2022-05, with the labels that each got.

#61 [2기-C 박현지] JPA 게시판 미션 - 엔티티 구성
  jpaboard/.gitignore
  jpaboard/build.gradle
  jpaboard/settings.gradle
  jpaboard/src/main/java/com/hyunji/jpaboard/JpaboardApplication.java
  jpaboard/src/main/java/com/hyunji/jpaboard/domain/post/domain/Post.java
  jpaboard/src/main/java/com/hyunji/jpaboard/domain/post/domain/PostRepository.java
  jpaboard/src/main/java/com/hyunji/jpaboard/domain/user/domain/User.java
  jpaboard/src/main/java/com/hyunji/jpaboard/domain/user/domain/UserRepository.java
  jpaboard/src/main/java/com/hyunji/jpaboard/model/BaseEntity.java
  jpaboard/src/main/resources/application.yml
  jpaboard/src/test/java/com/hyunji/jpaboard/JpaboardApplicationTests.java
  jpaboard/src/test/java/com/hyunji/jpaboard/domain/post/domain/PostTest.java
  jpaboard/src/test/java/com/hyunji/jpaboard/domain/post/domain/user/domain/UserTest.java
  jpaboard/src/test/resources/application-test.yml
Labels: Team-Wook

#59 [2기-C 남득윤] JPA 게시판 미션 - '엔티티 구성' 까지
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/study/board/BoardApplication.java
  src/main/java/com/study/board/domain/post/domain/Post.java
  src/main/java/com/study/board/domain/support/auditing/BaseEntity.java
  src/main/java/com/study/board/domain/user/domain/User.java
  src/main/resources/application.properties
  src/test/java/com/study/board/BoardApplicationTests.java
  src/test/java/com/study/board/domain/post/domain/PostTest.java
  src/test/java/com/study/board/domain/user/domain/UserTest.java
  src/test/java/com/study/board/fixture/Fixture.java
Labels: Team-Wook

#65 [2기-C] 유재희 프로젝트 생성, addPost기능 Controller 테스트 시리오
  board/.gitignore
  board/build.gradle
  board/gradle/wrapper/gradle-wrapper.jar
  board/gradle/wrapper/gradle-wrapper.properties
  board/gradlew
  board/gradlew.bat
  board/settings.gradle
  board/src/main/java/com/kdt/prgrms/board/BoardApplication.java
  board/src/main/resources/application.properties
  board/src/test/java/com/kdt/prgrms/board/controller/PostApiControllerTest.java
Labels: 🔥 매운맛, Team-Ray

#79 [2-C] 문정현 Spring Boot 4주차 게시판 과제 제출합니다~
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/index.adoc
  src/docs/index.pdf
  src/main/java/com/example/springbootboardjpa/DemoApplication.java
  src/main/java/com/example/springbootboardjpa/advice/RestAdvice.java
  src/main/java/com/example/springbootboardjpa/controller/PostRestController.java
  src/main/java/com/example/springbootboardjpa/converter/PostConverter.java
  src/main/java/com/example/springbootboardjpa/domain/BaseEntity.java
  src/main/java/com/example/springbootboardjpa/domain/Customer.java
  src/main/java/com/example/springbootboardjpa/domain/Post.java
  src/main/java/com/example/springbootboardjpa/dto/CustomerDto.java
  src/main/java/com/example/springbootboardjpa/dto/PostDto.java
  src/main/java/com/example/springbootboardjpa/repository/CustomerRepository.java
  src/main/java/com/example/springbootboardjpa/repository/PostRepository.java
  src/main/java/com/example/springbootboardjpa/response/ApiResponse.java
  src/main/java/com/example/springbootboardjpa/response/ResponseAop.java
  src/main/java/com/example/springbootboardjpa/service/PostService.java
  src/main/resources/application.yaml
  src/test/java/com/example/springbootboardjpa/DemoApplicationTests.java
  src/test/java/com/example/springbootboardjpa/controller/PostRestControllerTest.java
Labels: Team-Blackdog

#77 [2기 - C] 김산 프로젝트 생성, UserController 테스트 코드 작성
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/waterfogsw/springbootboardjpa/SpringbootBoardJpaApplication.java
  src/main/resources/application.yaml
  src/test/java/com/waterfogsw/springbootboardjpa/user/controller/UserApiControllerTest.java
Labels: Team-Ray

#78 [2기-C] 정하영 - 엔티티 생성, 연관관계 매핑
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/jpaboard/JpaBoardApplication.java
  src/main/java/com/example/jpaboard/domain/BaseTimeEntity.java
  src/main/java/com/example/jpaboard/domain/post/Post.java
  src/main/java/com/example/jpaboard/domain/post/PostRepository.java
  src/main/java/com/example/jpaboard/domain/user/User.java
  src/main/resources/application.yml
Labels: 🔥 매운맛, Team-Ray

#83 [2기-C] 김산 :sparkles: addUser 프로덕션 코드 작성
  build.gradle
  src/main/java/com/waterfogsw/springbootboardjpa/SpringbootBoardJpaApplication.java
  src/main/java/com/waterfogsw/springbootboardjpa/common/entity/BaseEntity.java
  src/main/java/com/waterfogsw/springbootboardjpa/common/exception/RestControllerAdvisor.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/controller/UserApiController.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/controller/dto/UserAddRequest.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/entity/User.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/service/DefaultUserService.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/service/UserService.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/util/UserConverter.java
  src/test/java/com/waterfogsw/springbootboardjpa/user/controller/UserApiControllerTest.java
Labels: Team-Ray

#85 [2기-C]유재희 엔티티 구성
  board/.gitignore
  board/build.gradle
  board/gradle/wrapper/gradle-wrapper.jar
  board/gradle/wrapper/gradle-wrapper.properties
  board/gradlew
  board/gradlew.bat
  board/settings.gradle
  board/src/main/java/com/kdt/prgrms/board/BoardApplication.java
  board/src/main/java/com/kdt/prgrms/board/entity/BaseEntity.java
  board/src/main/java/com/kdt/prgrms/board/entity/post/Post.java
  board/src/main/java/com/kdt/prgrms/board/entity/user/Hobby.java
  board/src/main/java/com/kdt/prgrms/board/entity/user/User.java
  board/src/main/resources/application.yml
Labels: 🔥 매운맛, Team-Ray

#88 [2기-C] 정하영 - ddl 제약 조건 명시 방법 변경
  build.gradle
  src/main/java/com/example/jpaboard/config/ServiceConfiguration.java
  src/main/java/com/example/jpaboard/domain/post/Post.java
  src/main/java/com/example/jpaboard/domain/user/User.java
Labels: Team-Ray

#89 [2기 - C] 김산 UserService, UserRepository 테스트 및 프로덕션 코드
  src/main/java/com/waterfogsw/springbootboardjpa/user/repository/UserRepository.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/service/DefaultUserService.java
  src/main/resources/application.yaml
  src/test/java/com/waterfogsw/springbootboardjpa/user/repository/UserRepositoryTest.java
  src/test/java/com/waterfogsw/springbootboardjpa/user/service/DefaultUserServiceTest.java
Labels: Team-Ray

#63 [2기-C 길근오] PostRepository 구현 & 테스트, 피드백 반영
  springboot/src/main/java/org/spring/notice/domain/BaseEntity.java
  springboot/src/main/java/org/spring/notice/domain/post/Post.java
  springboot/src/main/java/org/spring/notice/domain/post/PostRepository.java
  springboot/src/main/java/org/spring/notice/domain/user/User.java
  springboot/src/main/java/org/spring/notice/domain/user/UserRepository.java
  springboot/src/main/java/org/spring/notice/utils/UuidUtils.java
  springboot/src/test/java/org/spring/notice/domain/post/PostRepositoryTest.java
  springboot/src/test/java/org/spring/notice/domain/post/PostTest.java
  springboot/src/test/java/org/spring/notice/domain/user/UserTest.java
  springboot/src/test/java/org/spring/notice/fixture/Fixture.java
Labels: Team-Wook

#97 [2기-C] 정하영 - PostApiController 테스트와 구현입니다.
  build.gradle
  src/main/java/com/example/jpaboard/exception/CustomException.java
  src/main/java/com/example/jpaboard/exception/ErrorCode.java
  src/main/java/com/example/jpaboard/exception/ErrorResponse.java
  src/main/java/com/example/jpaboard/exception/ExceptionController.java
  src/main/java/com/example/jpaboard/service/post/PostService.java
  src/main/java/com/example/jpaboard/service/post/PostServiceImpl.java
  src/main/java/com/example/jpaboard/service/post/dto/PostResponse.java
  src/main/java/com/example/jpaboard/service/post/dto/PostSaveRequest.java
  src/main/java/com/example/jpaboard/service/post/dto/PostUpdateRequest.java
  src/main/java/com/example/jpaboard/web/controller/PostApiController.java
  src/test/java/com/example/jpaboard/web/controller/PostApiControllerTest.java
Labels: Team-Ray

#95 [2기-c]유재희 controller addUser 기능 구현
  board/src/main/java/com/kdt/prgrms/board/controller/UserRestController.java
  board/src/main/java/com/kdt/prgrms/board/dto/UserAddRequest.java
  board/src/main/java/com/kdt/prgrms/board/service/UserService.java
  board/src/test/java/com/kdt/prgrms/board/user/UserRestControllerTest.java
Labels: 🔥 매운맛, Team-Ray

#102 [2기-C] 정하영 - post 요청에 유저 정보 받도록 수정
  src/main/java/com/example/jpaboard/exception/ErrorCode.java
  src/main/java/com/example/jpaboard/service/dto/post/PostResponse.java
  src/main/java/com/example/jpaboard/service/dto/post/PostSaveRequest.java
  src/main/java/com/example/jpaboard/service/dto/post/PostUpdateRequest.java
  src/main/java/com/example/jpaboard/service/post/PostService.java
  src/main/java/com/example/jpaboard/service/post/PostServiceImpl.java
  src/main/java/com/example/jpaboard/web/controller/PostApiController.java
  src/test/java/com/example/jpaboard/web/controller/PostApiControllerTest.java
Labels: Team-Ray

#103 [2기-C]유재희 :sparkles: feat: Error 처리 추가
  board/src/main/java/com/kdt/prgrms/board/exception/ErrorCode.java
  board/src/main/java/com/kdt/prgrms/board/exception/ErrorResponse.java
  board/src/main/java/com/kdt/prgrms/board/exception/GlobalExceptionHandler.java
  board/src/main/java/com/kdt/prgrms/board/exception/custom/NotFoundException.java
Labels: 🔥 매운맛, Team-Ray

#108 [2기 - C] 김산 PostApiController 테스트 및 구현입니다.
  src/main/java/com/waterfogsw/springbootboardjpa/common/exception/RestControllerAdvisor.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/controller/PostApiController.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/controller/dto/PostAddRequest.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/controller/dto/PostResponse.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/controller/dto/PostUpdateRequest.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/entity/Post.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/service/DefaultPostService.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/service/PostService.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/util/PostConverter.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/entity/User.java
  src/test/java/com/waterfogsw/springbootboardjpa/post/controller/PostApiControllerTest.java
Labels: Team-Ray

#109 [2기-C]류영준 - User 등록 Controller 테스트 코드 작성 & 프로덕션 코드 틀 작성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/board/Application.java
  src/main/java/com/kdt/board/user/application/UserService.java
  src/main/java/com/kdt/board/user/application/UserServiceImpl.java
  src/main/java/com/kdt/board/user/application/dto/request/UserRegistrationRequestDto.java
  src/main/java/com/kdt/board/user/presentation/UserController.java
  src/test/java/com/kdt/board/user/application/UserControllerTest.java
Labels: Team-Ray

#111 [2기-C]유재희:sparkles: feat: UserService, Repository test 및 구현
  board/src/main/java/com/kdt/prgrms/board/entity/user/UserRepository.java
  board/src/main/java/com/kdt/prgrms/board/service/UserService.java
  board/src/test/java/com/kdt/prgrms/board/user/UserServiceTest.java
Labels: 🔥 매운맛, Team-Ray

#112 [2기 - C] 김산 :adhesive_bandage: user id 받도록 변경
  src/main/java/com/waterfogsw/springbootboardjpa/post/controller/PostApiController.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/controller/dto/PostUpdateRequest.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/service/DefaultPostService.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/service/PostService.java
  src/test/java/com/waterfogsw/springbootboardjpa/post/controller/PostApiControllerTest.java
Labels: Team-Ray

#114 [2기-C]류영준 - User 등록 Controller 프로덕션 코드 작성
  build.gradle
  src/main/java/com/kdt/board/common/advice/GlobalExceptionHandler.java
  src/main/java/com/kdt/board/common/dto/ErrorResponse.java
  src/main/java/com/kdt/board/common/exception/ErrorCode.java
  src/main/java/com/kdt/board/user/application/dto/request/UserRegistrationRequestDto.java
  src/main/java/com/kdt/board/user/presentation/UserController.java
  src/main/java/com/kdt/board/user/presentation/dto/request/UserRegistrationRequest.java
  src/test/java/com/kdt/board/user/application/UserControllerTest.java
Labels: Team-Ray

#115 [2기 - C] 김산 UserService 단건조회 테스트 및 프로덕션 코드
  src/main/java/com/waterfogsw/springbootboardjpa/common/exception/ResourceNotFoundException.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/service/DefaultUserService.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/service/UserService.java
  src/test/java/com/waterfogsw/springbootboardjpa/user/service/DefaultUserServiceTest.java
Labels: Team-Ray

#117 [2기-C]류영준 - User 등록 에러핸들링 추가
  src/main/java/com/kdt/board/common/advice/GlobalExceptionHandler.java
  src/main/java/com/kdt/board/common/dto/ErrorResponse.java
  src/main/java/com/kdt/board/common/exception/ErrorCode.java
  src/test/java/com/kdt/board/user/application/UserControllerTest.java
Labels: Team-Ray

#118 [2기-C] 정하영 - PostService 테스트와 구현
  src/main/java/com/example/jpaboard/domain/BaseTimeEntity.java
  src/main/java/com/example/jpaboard/domain/post/Post.java
  src/main/java/com/example/jpaboard/domain/post/PostRepository.java
  src/main/java/com/example/jpaboard/domain/user/User.java
  src/main/java/com/example/jpaboard/domain/user/UserRepository.java
  src/main/java/com/example/jpaboard/service/dto/post/PostResponse.java
  src/main/java/com/example/jpaboard/service/post/PostServiceImpl.java
  src/test/java/com/example/jpaboard/service/post/PostServiceTest.java
  src/test/java/com/example/jpaboard/web/controller/Common.java
  src/test/java/com/example/jpaboard/web/controller/PostApiControllerTest.java
Labels: Team-Ray

#116 [2기-C] 유재희 PostController Test및 프로덕션 코드 구현
  board/src/main/java/com/kdt/prgrms/board/controller/PostRestController.java
  board/src/main/java/com/kdt/prgrms/board/dto/PostAddRequest.java
  board/src/main/java/com/kdt/prgrms/board/dto/PostResponse.java
  board/src/main/java/com/kdt/prgrms/board/dto/PostUpdateRequest.java
  board/src/main/java/com/kdt/prgrms/board/entity/post/Post.java
  board/src/main/java/com/kdt/prgrms/board/entity/post/PostRepository.java
  board/src/main/java/com/kdt/prgrms/board/entity/user/User.java
  board/src/main/java/com/kdt/prgrms/board/exception/GlobalExceptionHandler.java
  board/src/main/java/com/kdt/prgrms/board/service/PostService.java
  board/src/main/java/com/kdt/prgrms/board/service/UserService.java
  board/src/test/java/com/kdt/prgrms/board/post/PostRestControllerTest.java
Labels: 🔥 매운맛, Team-Ray

#119 [2기-C] 정하영 - PostRepository 테스트와 구현
  src/main/java/com/example/jpaboard/domain/post/PostRepository.java
  src/test/java/com/example/jpaboard/domain/post/PostRepositoryTest.java
Labels: Team-Ray

#120 [2기-C] 정하영 - Transactional 어노테이션 수정
  src/main/java/com/example/jpaboard/service/post/PostServiceImpl.java
Labels: Team-Ray

#121 [2기-C] 정하영 - Post 엔티티 테스트와 프로덕션 코드 수정
  src/main/java/com/example/jpaboard/domain/post/Post.java
  src/test/java/com/example/jpaboard/domain/post/PostTest.java
  src/test/java/com/example/jpaboard/service/post/PostServiceTest.java
Labels: Team-Ray

#122 [2기-C]류영준 - User 등록 Service 테스트 코드 작성
  src/test/java/com/kdt/board/user/application/UserControllerTest.java
  src/test/java/com/kdt/board/user/domain/UserServiceTest.java
Labels: Team-Ray

#123 [2기-C] 정하영 - UserController 테스트와 구현
  src/main/java/com/example/jpaboard/domain/user/User.java
  src/main/java/com/example/jpaboard/service/dto/user/UserSaveRequest.java
  src/main/java/com/example/jpaboard/service/user/UserService.java
  src/main/java/com/example/jpaboard/service/user/UserServiceImpl.java
  src/main/java/com/example/jpaboard/web/controller/UserApiController.java
  src/test/java/com/example/jpaboard/web/controller/UserApiControllerTest.java
Labels: Team-Ray

#125 [2기-C] 정하영 - UserService 테스트와 구현입니다.
  src/main/java/com/example/jpaboard/domain/user/User.java
  src/main/java/com/example/jpaboard/service/user/UserServiceImpl.java
  src/test/java/com/example/jpaboard/service/post/PostServiceTest.java
  src/test/java/com/example/jpaboard/service/user/UserServiceTest.java
  src/test/java/com/example/jpaboard/web/controller/UserApiControllerTest.java
Labels: Team-Ray

#124 [2기-C]류영준 - User 등록 Service 프로덕션 코드 작성
  src/main/java/com/kdt/board/common/advice/GlobalExceptionHandler.java
  src/main/java/com/kdt/board/common/entity/BaseEntity.java
  src/main/java/com/kdt/board/common/exception/ErrorCode.java
  src/main/java/com/kdt/board/configuration/JpaAuditingConfiguration.java
  src/main/java/com/kdt/board/user/application/UserServiceImpl.java
  src/main/java/com/kdt/board/user/application/dto/request/UserRegistrationRequestDto.java
  src/main/java/com/kdt/board/user/domain/User.java
  src/main/java/com/kdt/board/user/presentation/dto/request/UserRegistrationRequest.java
Labels: Team-Ray

#126 [2기-C]류영준 - User 등록 Repository 테스트 코드 & 프로덕션 코드 작성
  src/main/java/com/kdt/board/common/entity/BaseEntity.java
  src/main/java/com/kdt/board/user/domain/repository/UserRepository.java
  src/test/java/com/kdt/board/user/domain/repository/UserRepositoryTest.java
Labels: Team-Ray

#129 [2기 - C] 김산 PostService 테스트 코드 및 프로덕션 코드 작성
  src/main/java/com/waterfogsw/springbootboardjpa/common/exception/AuthenticationException.java
  src/main/java/com/waterfogsw/springbootboardjpa/common/exception/RestControllerAdvisor.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/controller/PostApiController.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/entity/Post.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/repository/PostRepository.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/service/DefaultPostService.java
  src/main/java/com/waterfogsw/springbootboardjpa/post/service/PostService.java
  src/main/java/com/waterfogsw/springbootboardjpa/user/entity/User.java
  src/test/java/com/waterfogsw/springbootboardjpa/post/controller/PostApiControllerTest.java
  src/test/java/com/waterfogsw/springbootboardjpa/post/service/DefaultPostServiceTest.java
Labels: Team-Ray

#128 [2기-C]유재희 PostService 테스트 및 프로덕션 구현
  board/src/main/java/com/kdt/prgrms/board/dto/PostAddRequest.java
  board/src/main/java/com/kdt/prgrms/board/dto/PostResponse.java
  board/src/main/java/com/kdt/prgrms/board/entity/post/Post.java
  board/src/main/java/com/kdt/prgrms/board/entity/user/User.java
  board/src/main/java/com/kdt/prgrms/board/exception/ErrorCode.java
  board/src/main/java/com/kdt/prgrms/board/exception/GlobalExceptionHandler.java
  board/src/main/java/com/kdt/prgrms/board/exception/custom/AccessDeniedException.java
  board/src/main/java/com/kdt/prgrms/board/service/PostService.java
  board/src/test/java/com/kdt/prgrms/board/post/PostServiceTest.java
Labels: 🔥 매운맛, Team-Ray

#133 [2기 - C] 김산 PostRepository 테스트 및 프로덕션 코드 작성입니다
  src/main/java/com/waterfogsw/springbootboardjpa/post/repository/PostRepository.java
  src/test/java/com/waterfogsw/springbootboardjpa/post/repository/PostRepositoryTest.java
Labels: Team-Ray

#134 [2기-C]류영준 - Post CRU Controller 테스트 코드 & 프로덕션 코드 작성
  src/main/java/com/kdt/board/post/application/PostService.java
  src/main/java/com/kdt/board/post/application/PostServiceImpl.java
  src/main/java/com/kdt/board/post/application/dto/request/EditPostRequestDto.java
  src/main/java/com/kdt/board/post/application/dto/request/WritePostRequestDto.java
  src/main/java/com/kdt/board/post/application/dto/response/PostResponseDto.java
  src/main/java/com/kdt/board/post/presentation/PostController.java
  src/main/java/com/kdt/board/post/presentation/dto/request/EditPostRequest.java
  src/main/java/com/kdt/board/post/presentation/dto/request/WritePostRequest.java
  src/main/java/com/kdt/board/post/presentation/dto/response/PostResponse.java
  src/main/java/com/kdt/board/user/application/UserService.java
  src/main/java/com/kdt/board/user/application/UserServiceImpl.java
  src/main/java/com/kdt/board/user/application/dto/request/RegistrationUserRequestDto.java
  src/main/java/com/kdt/board/user/domain/User.java
  src/main/java/com/kdt/board/user/presentation/UserController.java
  src/main/java/com/kdt/board/user/presentation/dto/request/RegistrationUserRequest.java
  src/test/java/com/kdt/board/post/presentation/PostControllerTest.java
  src/test/java/com/kdt/board/user/application/UserControllerTest.java
  src/test/java/com/kdt/board/user/domain/UserServiceTest.java
  src/test/java/com/kdt/board/user/domain/repository/UserRepositoryTest.java
Labels: Team-Ray

#136 [2기-C]유도진 - User 관련 테스트 코드 작성
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/springboot-board-jpa.iml
  .idea/vcs.xml
  board-jpa/.gitignore
  board-jpa/build.gradle
  board-jpa/gradle/wrapper/gradle-wrapper.jar
  board-jpa/gradle/wrapper/gradle-wrapper.properties
  board-jpa/gradlew
  board-jpa/gradlew.bat
  board-jpa/settings.gradle
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/BoardJpaApplication.java
  board-jpa/src/main/resources/application.yml
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/user/controller/UserApiControllerTest.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/user/service/UserDefaultServiceTest.java
Labels: 🔥 매운맛, Team-Ray

#137 [2기-C]유도진 - User 관련 기능 구현
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/BoardJpaApplication.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/common/advice/DefaultControllerAdvice.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/common/entity/BaseEntity.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/common/exception/NotFoundException.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/user/controller/UserApiController.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/user/controller/dto/UserCreateRequest.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/user/entity/User.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/user/repository/UserRepository.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/user/service/UserDefaultService.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/user/service/UserService.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/user/service/dto/UserCreateDto.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/user/controller/UserApiControllerTest.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/user/service/UserDefaultServiceTest.java
Labels: 🔥 매운맛, Team-Ray

#139 [2기-C]유도진 - 게시글 생성 관련 테스트 코드 작성
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/post/controller/PostApiControllerTest.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/post/service/PostDefaultServiceTest.java
Labels: 🔥 매운맛, Team-Ray

#140 [2기-C]류영준 - Post CRU Service 테스트 코드 & 엔티티 단위 테스트 코드 & 프로덕션 코드 작성
  src/main/java/com/kdt/board/common/advice/GlobalExceptionHandler.java
  src/main/java/com/kdt/board/common/entity/BaseEntity.java
  src/main/java/com/kdt/board/common/exception/BusinessException.java
  src/main/java/com/kdt/board/common/exception/CannotEditPostException.java
  src/main/java/com/kdt/board/common/exception/ErrorCode.java
  src/main/java/com/kdt/board/common/exception/PostNotFoundException.java
  src/main/java/com/kdt/board/common/exception/UserNotFoundException.java
  src/main/java/com/kdt/board/post/application/PostServiceImpl.java
  src/main/java/com/kdt/board/post/application/dto/request/EditPostRequestDto.java
  src/main/java/com/kdt/board/post/application/dto/request/WritePostRequestDto.java
  src/main/java/com/kdt/board/post/application/dto/response/PostResponseDto.java
  src/main/java/com/kdt/board/post/domain/Post.java
  src/main/java/com/kdt/board/user/domain/User.java
  src/test/java/com/kdt/board/post/application/PostServiceTest.java
  src/test/java/com/kdt/board/post/domain/PostTest.java
  src/test/java/com/kdt/board/user/domain/UserServiceTest.java
  src/test/java/com/kdt/board/user/presentation/UserControllerTest.java
Labels: Team-Ray

#142 [2기-C]유도진 - Post 생성 기능 구현
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/common/entity/BaseEntity.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/controller/PostApiController.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/controller/dto/PostCreateRequest.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/entity/Post.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/respository/PostRepository.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/service/PostDefaultService.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/service/PostService.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/service/dto/PostCreateDto.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/user/service/UserDefaultService.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/post/controller/PostApiControllerTest.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/post/service/PostDefaultServiceTest.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/user/controller/UserApiControllerTest.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/user/service/UserDefaultServiceTest.java
Labels: 🔥 매운맛, Team-Ray

#143 [2기-C]류영준 - Post Repository 커스텀 JPQL 테스트 코드 & 프로덕션 코드 작성
  src/main/java/com/kdt/board/post/domain/repository/PostRepository.java
  src/test/java/com/kdt/board/post/domain/repository/PostRepositoryTest.java
  src/test/java/com/kdt/board/user/application/UserServiceTest.java
Labels: Team-Ray

#71 [2기-C 남득윤] JPA 게시판 미션 - 리포지토리 레이어, 서비스 레이어
  src/main/java/com/study/board/BoardApplication.java
  src/main/java/com/study/board/domain/base/BaseIdEntity.java
  src/main/java/com/study/board/domain/post/domain/Post.java
  src/main/java/com/study/board/domain/post/repository/PostRepository.java
  src/main/java/com/study/board/domain/post/service/PostService.java
  src/main/java/com/study/board/domain/post/service/PostServiceImpl.java
  src/main/java/com/study/board/domain/support/auditing/BaseEntity.java
  src/main/java/com/study/board/domain/user/domain/User.java
  src/main/java/com/study/board/domain/user/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/study/board/domain/post/domain/PostTest.java
  src/test/java/com/study/board/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/study/board/domain/post/service/PostServiceImplTest.java
  src/test/java/com/study/board/domain/user/domain/UserTest.java
  src/test/java/com/study/board/fixture/Fixture.java
Labels: Team-Wook

#145 [2기-C]유도진 - Id를 이용한 Post 검색 기능 구현
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/common/advice/DefaultControllerAdvice.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/common/entity/BaseEntity.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/controller/PostApiController.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/entity/Post.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/service/PostDefaultService.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/service/PostService.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/service/dto/PostResponseDto.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/post/controller/PostApiControllerTest.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/post/service/PostDefaultServiceTest.java
Labels: 🔥 매운맛, Team-Ray

#150 [2기-C 남득윤] JPA 게시판 미션 - 컨트롤러 레이어, 문서화
  pom.xml
  src/docs/asciidoc/Post-API.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/overview.adoc
  src/main/java/com/study/board/controller/GeneralExceptionHandler.java
  src/main/java/com/study/board/controller/PostRestController.java
  src/main/java/com/study/board/controller/dto/PostRequest.java
  src/main/java/com/study/board/controller/dto/PostResponse.java
  src/main/java/com/study/board/domain/post/service/PostService.java
  src/main/java/com/study/board/domain/post/service/PostServiceImpl.java
  src/main/java/com/study/board/domain/user/repository/UserRepository.java
  src/test/java/com/study/board/controller/post/PostRestControllerTest.java
  src/test/java/com/study/board/controller/support/ControllerTest.java
  src/test/java/com/study/board/controller/support/RestDocsConfig.java
  src/test/java/com/study/board/controller/support/RestDocsTestSupport.java
  src/test/java/com/study/board/domain/post/service/PostServiceImplTest.java
  src/test/java/com/study/board/domain/user/domain/UserTest.java
Labels: Team-Wook

#156 [2기-C]유도진 - 페이징을 이용한 Post 전체 조회 기능 구현
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/controller/PostApiController.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/service/PostDefaultService.java
  board-jpa/src/main/java/com/dojinyou/devcourse/boardjpa/post/service/PostService.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/post/controller/PostApiControllerTest.java
  board-jpa/src/test/java/com/dojinyou/devcourse/boardjpa/post/service/PostDefaultServiceTest.java
Labels: 🔥 매운맛, Team-Ray

#81 [2기-P 이예림] JPA 게시판 구현
  README.md
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/example/demo/controller/PostController.java
  src/main/java/com/example/demo/converter/PostConverter.java
  src/main/java/com/example/demo/domain/BasedTimeEntity.java
  src/main/java/com/example/demo/domain/Post.java
  src/main/java/com/example/demo/domain/User.java
  src/main/java/com/example/demo/dto/PostDto.java
  src/main/java/com/example/demo/dto/UserDto.java
  src/main/java/com/example/demo/exception/ErrorResponse.java
  src/main/java/com/example/demo/exception/ErrorStatus.java
  src/main/java/com/example/demo/exception/PostExceptionHandler.java
  src/main/java/com/example/demo/exception/PostNotFoundException.java
  src/main/java/com/example/demo/repository/PostRepository.java
  src/main/java/com/example/demo/service/PostService.java
  src/main/resources/application.yaml
  src/test/java/com/example/demo/controller/PostControllerTest.java
  src/test/java/com/example/demo/service/PostServiceTest.java
Labels: Team-Hoon, 🔥 매운맛
