Repository prgrms-be-devcourse/springboot-board-jpa, pull requests merged in 2022-12, with the labels that each got.

#164 [2기-P] 박혜빈 JPA 게시판 구현 코드 리뷰 부탁드립니다 😊
  .gitignore
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/org/programmers/kdtboard/SpringbootBoardJpaApplication.java
  src/main/java/org/programmers/kdtboard/controller/PostController.java
  src/main/java/org/programmers/kdtboard/controller/UserController.java
  src/main/java/org/programmers/kdtboard/controller/response/ApiResponse.java
  src/main/java/org/programmers/kdtboard/controller/response/ErrorCode.java
  src/main/java/org/programmers/kdtboard/controller/response/ErrorResponse.java
  src/main/java/org/programmers/kdtboard/converter/PostConverter.java
  src/main/java/org/programmers/kdtboard/converter/UserConverter.java
  src/main/java/org/programmers/kdtboard/domain/BaseEntity.java
  src/main/java/org/programmers/kdtboard/domain/JpaAuditingConfig.java
  src/main/java/org/programmers/kdtboard/domain/post/Post.java
  src/main/java/org/programmers/kdtboard/domain/post/PostRepository.java
  src/main/java/org/programmers/kdtboard/domain/user/User.java
  src/main/java/org/programmers/kdtboard/domain/user/UserRepository.java
  src/main/java/org/programmers/kdtboard/dto/PostDto.java
  src/main/java/org/programmers/kdtboard/dto/UserDto.java
  src/main/java/org/programmers/kdtboard/exception/GlobalExceptionHandler.java
  src/main/java/org/programmers/kdtboard/exception/NotFoundEntityByIdException.java
  src/main/java/org/programmers/kdtboard/exception/NotValidException.java
  src/main/java/org/programmers/kdtboard/service/PostService.java
  src/main/java/org/programmers/kdtboard/service/UserService.java
  src/main/resources/application.yml
  src/test/java/org/programmers/kdtboard/SpringbootBoardJpaApplicationTests.java
  src/test/java/org/programmers/kdtboard/controller/PostControllerTest.java
Labels: 🔥 매운맛, Team-Kyu

#163 [2기-P] 김형욱 SpringBoot-Board-JPA 미션 제출합니다.
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/prgrms/work/SpringbootBoardJpaApplication.java
  src/main/java/com/prgrms/work/common/BaseEntity.java
  src/main/java/com/prgrms/work/controller/PostErrorController.java
  src/main/java/com/prgrms/work/controller/PostRestController.java
  src/main/java/com/prgrms/work/controller/dto/ApiResponse.java
  src/main/java/com/prgrms/work/controller/dto/MemberRequest.java
  src/main/java/com/prgrms/work/controller/dto/PostRequest.java
  src/main/java/com/prgrms/work/controller/dto/PostResponse.java
  src/main/java/com/prgrms/work/error/EntityInvalidException.java
  src/main/java/com/prgrms/work/error/PostNotFoundException.java
  src/main/java/com/prgrms/work/post/domain/Post.java
  src/main/java/com/prgrms/work/post/repository/PostRepository.java
  src/main/java/com/prgrms/work/post/service/PostService.java
  src/main/java/com/prgrms/work/post/service/PostServiceImpl.java
  src/main/java/com/prgrms/work/user/domain/User.java
  src/main/resources/application.yml
  src/test/java/com/prgrms/work/SpringbootBoardJpaApplicationTests.java
  src/test/java/com/prgrms/work/post/domain/PostTest.java
  src/test/java/com/prgrms/work/post/repository/PostRepositoryTest.java
  src/test/java/com/prgrms/work/post/service/PostServiceTest.java
  src/test/java/com/prgrms/work/user/domain/UserTest.java
Labels: 🔥 매운맛, Team-Kyu

#168 [3기-C 김영수] JPA 게시판 미션 구현 리뷰 부탁드립니다.
  board/board/.gitignore
  board/board/BOOT-INF/classes/static/docs/index.html
  board/board/build.gradle
  board/board/gradle/wrapper/gradle-wrapper.jar
  board/board/gradle/wrapper/gradle-wrapper.properties
  board/board/gradlew
  board/board/gradlew.bat
  board/board/settings.gradle
  board/board/src/docs/asciidoc/index.adoc
  board/board/src/main/java/com/ys/board/BoardApplication.java
  board/board/src/main/java/com/ys/board/common/RestGlobalExceptionHandler.java
  board/board/src/main/java/com/ys/board/common/exception/EntityNotFoundException.java
  board/board/src/main/java/com/ys/board/common/response/ErrorResponse.java
  board/board/src/main/java/com/ys/board/config/JpaConfig.java
  board/board/src/main/java/com/ys/board/domain/base/AbstractCreatedColumn.java
  board/board/src/main/java/com/ys/board/domain/post/api/PostController.java
  board/board/src/main/java/com/ys/board/domain/post/api/PostCreateRequest.java
  board/board/src/main/java/com/ys/board/domain/post/api/PostCreateResponse.java
  board/board/src/main/java/com/ys/board/domain/post/api/PostResponse.java
  board/board/src/main/java/com/ys/board/domain/post/api/PostResponses.java
  board/board/src/main/java/com/ys/board/domain/post/api/PostUpdateRequest.java
  board/board/src/main/java/com/ys/board/domain/post/api/PostsRequest.java
  board/board/src/main/java/com/ys/board/domain/post/model/Post.java
  board/board/src/main/java/com/ys/board/domain/post/repository/PostRepository.java
  board/board/src/main/java/com/ys/board/domain/post/service/PostService.java
  board/board/src/main/java/com/ys/board/domain/post/service/PostServiceFacade.java
  board/board/src/main/java/com/ys/board/domain/user/DuplicateNameException.java
  board/board/src/main/java/com/ys/board/domain/user/api/UserController.java
  board/board/src/main/java/com/ys/board/domain/user/api/UserCreateRequest.java
  board/board/src/main/java/com/ys/board/domain/user/api/UserCreateResponse.java
  board/board/src/main/java/com/ys/board/domain/user/model/User.java
  board/board/src/main/java/com/ys/board/domain/user/repository/UserRepository.java
  board/board/src/main/java/com/ys/board/domain/user/service/UserService.java
  board/board/src/main/resources/application.yml
  board/board/src/main/resources/static/docs/index.html
  board/board/src/test/java/com/ys/board/BoardApplicationTests.java
  board/board/src/test/java/com/ys/board/domain/post/api/PostControllerTest.java
  board/board/src/test/java/com/ys/board/domain/post/model/PostTest.java
  board/board/src/test/java/com/ys/board/domain/post/service/PostServiceFacadeTest.java
  board/board/src/test/java/com/ys/board/domain/post/service/PostServiceSliceTest.java
  board/board/src/test/java/com/ys/board/domain/user/api/UserControllerTest.java
  board/board/src/test/java/com/ys/board/domain/user/model/UserTest.java
  board/board/src/test/java/com/ys/board/domain/user/service/UserServiceSliceTest.java
Labels: 🔥 매운맛, Team-Blackdog

#101 [2-C]방은혁 'JPA 게시판 구현 미션' 코드 리뷰 요청합니다!
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/main/java/com/prgrms/hyuk/Application.java
  src/main/java/com/prgrms/hyuk/domain/BaseEntity.java
  src/main/java/com/prgrms/hyuk/domain/post/Content.java
  src/main/java/com/prgrms/hyuk/domain/post/Post.java
  src/main/java/com/prgrms/hyuk/domain/post/Title.java
  src/main/java/com/prgrms/hyuk/domain/user/Age.java
  src/main/java/com/prgrms/hyuk/domain/user/Hobby.java
  src/main/java/com/prgrms/hyuk/domain/user/Name.java
  src/main/java/com/prgrms/hyuk/domain/user/Posts.java
  src/main/java/com/prgrms/hyuk/domain/user/User.java
  src/main/java/com/prgrms/hyuk/dto/ApiResponse.java
  src/main/java/com/prgrms/hyuk/dto/PostCreateRequest.java
  src/main/java/com/prgrms/hyuk/dto/PostDto.java
  src/main/java/com/prgrms/hyuk/dto/PostUpdateRequest.java
  src/main/java/com/prgrms/hyuk/dto/UserDto.java
  src/main/java/com/prgrms/hyuk/exception/AgeOutOfRangeException.java
  src/main/java/com/prgrms/hyuk/exception/ClientException.java
  src/main/java/com/prgrms/hyuk/exception/ExceptionMessage.java
  src/main/java/com/prgrms/hyuk/exception/InvalidContentFormatException.java
  src/main/java/com/prgrms/hyuk/exception/InvalidNameFormatException.java
  src/main/java/com/prgrms/hyuk/exception/InvalidPostIdException.java
  src/main/java/com/prgrms/hyuk/exception/InvalidTitleFormatException.java
  src/main/java/com/prgrms/hyuk/repository/PostCustomRepository.java
  src/main/java/com/prgrms/hyuk/repository/PostCustomRepositoryImpl.java
  src/main/java/com/prgrms/hyuk/repository/PostRepository.java
  src/main/java/com/prgrms/hyuk/service/PostService.java
  src/main/java/com/prgrms/hyuk/service/converter/Converter.java
  src/main/java/com/prgrms/hyuk/web/controller/PostController.java
  src/main/java/com/prgrms/hyuk/web/exhandler/ApiExceptionController.java
  src/main/resources/application.yml
  src/test/java/com/prgrms/hyuk/ApplicationTest.java
  src/test/java/com/prgrms/hyuk/IntegrationTest.java
  src/test/java/com/prgrms/hyuk/controller/PostControllerTest.java
  src/test/java/com/prgrms/hyuk/domain/MappingTest.java
  src/test/java/com/prgrms/hyuk/domain/post/ContentTest.java
  src/test/java/com/prgrms/hyuk/domain/post/PostTest.java
  src/test/java/com/prgrms/hyuk/domain/post/TitleTest.java
  src/test/java/com/prgrms/hyuk/domain/user/AgeTest.java
  src/test/java/com/prgrms/hyuk/domain/user/NameTest.java
  src/test/java/com/prgrms/hyuk/domain/user/PostsTest.java
  src/test/java/com/prgrms/hyuk/domain/user/UserTest.java
  src/test/java/com/prgrms/hyuk/repository/PostRepositoryTest.java
  src/test/java/com/prgrms/hyuk/service/PostServiceIntegrationTest.java
  src/test/resources/application.yml
Labels: 🔥 매운맛, Team-Marco

#127 [2기-C 김지웅] 스프링부트 JPA 게시판 과제 제출
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/programmers/board/BoardApplication.java
  src/main/java/org/programmers/board/controller/BoardApiController.java
  src/main/java/org/programmers/board/controller/UserApiController.java
  src/main/java/org/programmers/board/dto/BoardCreateRequest.java
  src/main/java/org/programmers/board/dto/BoardResponse.java
  src/main/java/org/programmers/board/dto/BoardUpdateRequest.java
  src/main/java/org/programmers/board/dto/MemberCreateRequest.java
  src/main/java/org/programmers/board/dto/MemberCreateResponse.java
  src/main/java/org/programmers/board/dto/UserDTO.java
  src/main/java/org/programmers/board/entity/BaseEntity.java
  src/main/java/org/programmers/board/entity/Board.java
  src/main/java/org/programmers/board/entity/Boards.java
  src/main/java/org/programmers/board/entity/User.java
  src/main/java/org/programmers/board/entity/vo/Content.java
  src/main/java/org/programmers/board/entity/vo/Name.java
  src/main/java/org/programmers/board/entity/vo/Title.java
  src/main/java/org/programmers/board/exception/EmptyContentException.java
  src/main/java/org/programmers/board/exception/EmptyTitleException.java
  src/main/java/org/programmers/board/exception/NoBoardException.java
  src/main/java/org/programmers/board/exception/TooLongNameException.java
  src/main/java/org/programmers/board/exception/handler/BoardApiExceptionController.java
  src/main/java/org/programmers/board/exception/handler/ErrorResponse.java
  src/main/java/org/programmers/board/repository/BoardRepository.java
  src/main/java/org/programmers/board/repository/UserRepository.java
  src/main/java/org/programmers/board/service/BoardService.java
  src/main/java/org/programmers/board/service/UserService.java
  src/main/resources/application.yml
  src/test/java/org/programmers/board/BoardApplicationTests.java
  src/test/java/org/programmers/board/controller/BoardApiControllerTest.java
  src/test/java/org/programmers/board/entity/vo/ContentTest.java
  src/test/java/org/programmers/board/entity/vo/NameTest.java
  src/test/java/org/programmers/board/entity/vo/TitleTest.java
  src/test/java/org/programmers/board/repository/BoardRepositoryTest.java
  src/test/java/org/programmers/board/repository/UserRepositoryTest.java
  src/test/java/org/programmers/board/service/BoardServiceTest.java
  src/test/java/org/programmers/board/service/UserServiceTest.java
Labels: Team-Marco

#132 [2-C] 강태산 JPA 게시판 구현 미션 제출
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/asciidoc/index.adoc
  src/main/java/com/prgrms/boardapp/BoardappApplication.java
  src/main/java/com/prgrms/boardapp/constant/PostErrMsg.java
  src/main/java/com/prgrms/boardapp/constant/UserErrMsg.java
  src/main/java/com/prgrms/boardapp/controller/PostController.java
  src/main/java/com/prgrms/boardapp/dto/PostRequest.java
  src/main/java/com/prgrms/boardapp/dto/PostResponse.java
  src/main/java/com/prgrms/boardapp/dto/UserResponse.java
  src/main/java/com/prgrms/boardapp/exception/ApiControllerAdvice.java
  src/main/java/com/prgrms/boardapp/model/CommonEmbeddable.java
  src/main/java/com/prgrms/boardapp/model/Post.java
  src/main/java/com/prgrms/boardapp/model/Posts.java
  src/main/java/com/prgrms/boardapp/model/User.java
  src/main/java/com/prgrms/boardapp/repository/PostRepository.java
  src/main/java/com/prgrms/boardapp/repository/UserRepository.java
  src/main/java/com/prgrms/boardapp/service/Converter.java
  src/main/java/com/prgrms/boardapp/service/PostService.java
  src/main/java/com/prgrms/boardapp/util/CommonValidate.java
  src/main/resources/application.yml
  src/test/java/com/prgrms/boardapp/common/EntityManagerTest.java
  src/test/java/com/prgrms/boardapp/common/PostCreateUtil.java
  src/test/java/com/prgrms/boardapp/common/UserCreateUtil.java
  src/test/java/com/prgrms/boardapp/controller/DocumentInfo.java
  src/test/java/com/prgrms/boardapp/controller/PageableInfo.java
  src/test/java/com/prgrms/boardapp/controller/PostControllerTest.java
  src/test/java/com/prgrms/boardapp/model/CommonEmbeddableTest.java
  src/test/java/com/prgrms/boardapp/model/PostConvenienceMethodTest.java
  src/test/java/com/prgrms/boardapp/model/PostTest.java
  src/test/java/com/prgrms/boardapp/model/UserConvenienceMethodTest.java
  src/test/java/com/prgrms/boardapp/model/UserTest.java
  src/test/java/com/prgrms/boardapp/repository/PostRepositoryTest.java
  src/test/java/com/prgrms/boardapp/repository/UserRepositoryTest.java
  src/test/java/com/prgrms/boardapp/service/PostServiceTest.java
Labels: 🔥 매운맛, Team-Marco

#175 [3기-C 이건우] JPA 게시판 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/devcourse/springjpaboard/SpringJpaBoardApplication.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/Post.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/api/PostController.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/application/PostFacade.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/application/PostService.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/application/converter/PostConverter.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/dto/PostCreateRequest.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/dto/PostCreateResponse.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/dto/PostSearchResponse.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/dto/PostSearchResponses.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/dto/PostUpdateRequest.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/exeception/PostNotFoundException.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/post/repository/PostRepository.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/user/User.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/user/api/UserController.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/user/application/UserFacade.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/user/application/UserService.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/user/application/converter/UserConverter.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/user/dto/UserCreateRequest.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/user/exeception/UserNotFoundException.java
  src/main/java/com/prgrms/devcourse/springjpaboard/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/devcourse/springjpaboard/global/common/base/BaseEntity.java
  src/main/java/com/prgrms/devcourse/springjpaboard/global/config/JpaAuditingConfig.java
  src/main/java/com/prgrms/devcourse/springjpaboard/global/error/EntityNotFoundException.java
  src/main/java/com/prgrms/devcourse/springjpaboard/global/error/ErrorResponse.java
  src/main/java/com/prgrms/devcourse/springjpaboard/global/error/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/static/docs/index.html
  src/test/java/com/prgrms/devcourse/springjpaboard/SpringJpaBoardApplicationTests.java
  src/test/java/com/prgrms/devcourse/springjpaboard/domain/post/PostTest.java
  src/test/java/com/prgrms/devcourse/springjpaboard/domain/post/TestPostObjectProvider.java
  src/test/java/com/prgrms/devcourse/springjpaboard/domain/post/api/PostControllerDocTest.java
  src/test/java/com/prgrms/devcourse/springjpaboard/domain/post/api/PostControllerTest.java
  src/test/java/com/prgrms/devcourse/springjpaboard/domain/post/application/PostFacadeTest.java
  src/test/java/com/prgrms/devcourse/springjpaboard/domain/post/application/PostServiceTest.java
  src/test/java/com/prgrms/devcourse/springjpaboard/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/prgrms/devcourse/springjpaboard/domain/user/TestUserObjectProvider.java
  src/test/java/com/prgrms/devcourse/springjpaboard/domain/user/UserTest.java
Labels: 💧 순한맛, Team-Blackdog

#179 [3기-C 이택승] JPA 게시판 구현 미션 제출합니다
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  sprinboot-board/.gitignore
  sprinboot-board/build.gradle
  sprinboot-board/gradle/wrapper/gradle-wrapper.jar
  sprinboot-board/gradle/wrapper/gradle-wrapper.properties
  sprinboot-board/gradlew
  sprinboot-board/gradlew.bat
  sprinboot-board/settings.gradle
  sprinboot-board/src/docs/asciidoc/index.adoc
  sprinboot-board/src/main/java/com/prgrms/java/PostController.java
  sprinboot-board/src/main/java/com/prgrms/java/PostService.java
  sprinboot-board/src/main/java/com/prgrms/java/SpringbootBoardApplication.java
  sprinboot-board/src/main/java/com/prgrms/java/domain/BaseEntity.java
  sprinboot-board/src/main/java/com/prgrms/java/domain/HobbyType.java
  sprinboot-board/src/main/java/com/prgrms/java/domain/Post.java
  sprinboot-board/src/main/java/com/prgrms/java/domain/User.java
  sprinboot-board/src/main/java/com/prgrms/java/dto/CreatePostRequest.java
  sprinboot-board/src/main/java/com/prgrms/java/dto/CreatePostResponse.java
  sprinboot-board/src/main/java/com/prgrms/java/dto/GetPostDetailsResponse.java
  sprinboot-board/src/main/java/com/prgrms/java/dto/GetPostsResponse.java
  sprinboot-board/src/main/java/com/prgrms/java/dto/ModifyPostRequest.java
  sprinboot-board/src/main/java/com/prgrms/java/dto/ModifyPostResponse.java
  sprinboot-board/src/main/java/com/prgrms/java/exception/ErrorResponse.java
  sprinboot-board/src/main/java/com/prgrms/java/exception/GlobalExceptionHandler.java
  sprinboot-board/src/main/java/com/prgrms/java/exception/ResourceNotFountException.java
  sprinboot-board/src/main/java/com/prgrms/java/repository/PostRepository.java
  sprinboot-board/src/main/java/com/prgrms/java/repository/UserRepository.java
  sprinboot-board/src/main/resources/application.yml
  sprinboot-board/src/main/resources/static/docs/index.html
  sprinboot-board/src/test/java/com/prgrms/java/PostControllerTest.java
  sprinboot-board/src/test/java/com/prgrms/java/PostServiceTest.java
  sprinboot-board/src/test/java/com/prgrms/java/SpringbootBoardApplicationTests.java
  sprinboot-board/src/test/java/com/prgrms/java/domain/PostTest.java
  sprinboot-board/src/test/java/com/prgrms/java/domain/UserTest.java
  sprinboot-board/src/test/resources/aplication.yml
Labels: Team-Allen, 🔥 매운맛

#180 [3기-C 이수린] Spring JPA 게시판 미션 리뷰 부탁드립니다!
  .gitignore
  build.gradle
  src/main/java/com/spring/board/springboard/SpringBoardApplication.java
  src/main/java/com/spring/board/springboard/domain/Response.java
  src/main/java/com/spring/board/springboard/post/controller/PostController.java
  src/main/java/com/spring/board/springboard/post/domain/Post.java
  src/main/java/com/spring/board/springboard/post/domain/dto/RequestPostDto.java
  src/main/java/com/spring/board/springboard/post/domain/dto/ResponsePostDto.java
  src/main/java/com/spring/board/springboard/post/exception/NoPostException.java
  src/main/java/com/spring/board/springboard/post/repository/PostRepository.java
  src/main/java/com/spring/board/springboard/post/service/PostService.java
  src/main/java/com/spring/board/springboard/user/domain/Hobby.java
  src/main/java/com/spring/board/springboard/user/domain/Member.java
  src/main/java/com/spring/board/springboard/user/domain/MemberDto.java
  src/main/java/com/spring/board/springboard/user/domain/MemberResponseDto.java
  src/main/java/com/spring/board/springboard/user/exception/NoMemberException.java
  src/main/java/com/spring/board/springboard/user/repository/MemberRepository.java
  src/main/java/com/spring/board/springboard/user/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/static/docs/api.html
  src/test/java/com/spring/board/springboard/SpringBoardApplicationTests.java
  src/test/java/com/spring/board/springboard/post/controller/PostControllerTest.java
  src/test/java/com/spring/board/springboard/post/repository/PostRepositoryTest.java
  src/test/java/com/spring/board/springboard/post/service/PostServiceTest.java
  src/test/java/com/spring/board/springboard/user/domain/MemberTest.java
Labels: Team-Allen, 🔥 매운맛

#181 [3기-C 김환] JPA 게시판 구현 미션 제출합니다
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/board/BoardApplication.java
  src/main/java/com/example/board/common/exception/BadRequestException.java
  src/main/java/com/example/board/common/exception/NotFoundException.java
  src/main/java/com/example/board/domain/common/entity/BaseEntity.java
  src/main/java/com/example/board/domain/common/entity/BaseTimeEntity.java
  src/main/java/com/example/board/domain/common/entity/RequestBodyAuditorAware.java
  src/main/java/com/example/board/domain/member/controller/MemberController.java
  src/main/java/com/example/board/domain/member/dto/MemberRequest.java
  src/main/java/com/example/board/domain/member/dto/MemberResponse.java
  src/main/java/com/example/board/domain/member/entity/Member.java
  src/main/java/com/example/board/domain/member/repository/MemberRepository.java
  src/main/java/com/example/board/domain/member/service/MemberService.java
  src/main/java/com/example/board/domain/post/controller/PostController.java
  src/main/java/com/example/board/domain/post/dto/PostRequest.java
  src/main/java/com/example/board/domain/post/dto/PostResponse.java
  src/main/java/com/example/board/domain/post/entity/Post.java
  src/main/java/com/example/board/domain/post/repository/PostRepository.java
  src/main/java/com/example/board/domain/post/service/PostService.java
  src/main/resources/application.yml
  src/test/java/com/example/board/BoardApplicationTests.java
  src/test/java/com/example/board/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/board/domain/member/entity/MemberTest.java
  src/test/java/com/example/board/domain/post/controller/PostControllerTest.java
  src/test/java/com/example/board/domain/post/entity/PostTest.java
Labels: Team-Allen, 🔥 매운맛

#186 [3기-C 서예원] JPA게시판 구현 미션 제출합니다
  .gitignore
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/BoardApplication.java
  src/main/java/com/prgrms/domain/BaseEntity.java
  src/main/java/com/prgrms/domain/post/Post.java
  src/main/java/com/prgrms/domain/post/PostController.java
  src/main/java/com/prgrms/domain/post/PostRepository.java
  src/main/java/com/prgrms/domain/post/PostService.java
  src/main/java/com/prgrms/domain/user/User.java
  src/main/java/com/prgrms/domain/user/UserController.java
  src/main/java/com/prgrms/domain/user/UserRepository.java
  src/main/java/com/prgrms/domain/user/UserService.java
  src/main/java/com/prgrms/dto/PostDto.java
  src/main/java/com/prgrms/dto/UserDto.java
  src/main/java/com/prgrms/exception/ErrorCode.java
  src/main/java/com/prgrms/exception/ErrorResponse.java
  src/main/java/com/prgrms/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/exception/customException/PostNotFoundException.java
  src/main/java/com/prgrms/exception/customException/UserNotFoundException.java
  src/main/resources/application.yml
  src/main/resources/static/docs/index.html
  src/test/java/com/prgrms/domain/post/PostControllerTest.java
  src/test/resources/application.yml
Labels: Team-Allen, 🔥 매운맛

#188 [3기-C 김선호] JPA 게시판 구현 미션 제출합니다
  .gitignore
  build.gradle
  settings.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/devcourse/board/BoardApplication.java
  src/main/java/devcourse/board/api/MemberApiController.java
  src/main/java/devcourse/board/api/PostApiController.java
  src/main/java/devcourse/board/api/model/CreateDataResponse.java
  src/main/java/devcourse/board/domain/member/MemberRepository.java
  src/main/java/devcourse/board/domain/member/MemberService.java
  src/main/java/devcourse/board/domain/member/model/Member.java
  src/main/java/devcourse/board/domain/member/model/MemberJoinRequest.java
  src/main/java/devcourse/board/domain/post/PostRepository.java
  src/main/java/devcourse/board/domain/post/PostService.java
  src/main/java/devcourse/board/domain/post/model/MultiplePostResponse.java
  src/main/java/devcourse/board/domain/post/model/Post.java
  src/main/java/devcourse/board/domain/post/model/PostCreationRequest.java
  src/main/java/devcourse/board/domain/post/model/PostResponse.java
  src/main/java/devcourse/board/domain/post/model/PostUpdateRequest.java
  src/main/resources/application.yaml
  src/main/resources/static/docs/index.html
  src/main/resources/static/index.html
  src/test/java/devcourse/board/BoardApplicationTests.java
  src/test/java/devcourse/board/api/MemberApiControllerTest.java
  src/test/java/devcourse/board/api/PostApiControllerTest.java
  src/test/java/devcourse/board/domain/member/MemberRepositoryTest.java
  src/test/java/devcourse/board/domain/member/MemberServiceTest.java
  src/test/java/devcourse/board/domain/member/model/MemberTest.java
  src/test/java/devcourse/board/domain/post/PostServiceTest.java
  src/test/resources/application.yaml
Labels: Team-Allen, 🔥 매운맛
