Repository prgrms-be-devcourse/springboot-board-jpa, pull requests merged in 2022-08, with the labels that each got.

#74 [2기-C 박형근] JPA 게시판 미션
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/asciidoc/post-edit.adoc
  src/asciidoc/post-find-all.adoc
  src/asciidoc/post-find-one.adoc
  src/asciidoc/post-save.adoc
  src/asciidoc/user-edit.adoc
  src/asciidoc/user-find-all.adoc
  src/asciidoc/user-find-id.adoc
  src/asciidoc/user-find-name.adoc
  src/asciidoc/user-save.adoc
  src/main/java/com/kdt/boardMission/BoardMissionApplication.java
  src/main/java/com/kdt/boardMission/aop/RestExceptionHandler.java
  src/main/java/com/kdt/boardMission/controller/PostRestController.java
  src/main/java/com/kdt/boardMission/controller/UserRestController.java
  src/main/java/com/kdt/boardMission/domain/Post.java
  src/main/java/com/kdt/boardMission/domain/User.java
  src/main/java/com/kdt/boardMission/domain/superClass/BaseEntity.java
  src/main/java/com/kdt/boardMission/dto/CreatePostDto.java
  src/main/java/com/kdt/boardMission/dto/PostDto.java
  src/main/java/com/kdt/boardMission/dto/UserDto.java
  src/main/java/com/kdt/boardMission/repository/PostRepository.java
  src/main/java/com/kdt/boardMission/repository/UserRepository.java
  src/main/java/com/kdt/boardMission/service/PostService.java
  src/main/java/com/kdt/boardMission/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/kdt/boardMission/BoardMissionApplicationTests.java
  src/test/java/com/kdt/boardMission/controller/PostRestControllerTest.java
  src/test/java/com/kdt/boardMission/controller/UserRestControllerTest.java
  src/test/java/com/kdt/boardMission/domain/DomainTest.java
  src/test/java/com/kdt/boardMission/repository/PostRepositoryTest.java
  src/test/java/com/kdt/boardMission/repository/UserRepositoryTest.java
  src/test/java/com/kdt/boardMission/service/PostServiceTest.java
  src/test/java/com/kdt/boardMission/service/UserServiceTest.java
Labels: 🔥 매운맛, Team-F

#160 [2기-P] 최인창 SpringBoot Board JPA Mission 제출
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/main/java/org/programmers/springboardjpa/SpringBoardApplication.java
  src/main/java/org/programmers/springboardjpa/domain/model/BaseEntity.java
  src/main/java/org/programmers/springboardjpa/domain/post/api/PostApi.java
  src/main/java/org/programmers/springboardjpa/domain/post/domain/Post.java
  src/main/java/org/programmers/springboardjpa/domain/post/dto/PostRequest.java
  src/main/java/org/programmers/springboardjpa/domain/post/dto/PostResponse.java
  src/main/java/org/programmers/springboardjpa/domain/post/exception/NotExistPostException.java
  src/main/java/org/programmers/springboardjpa/domain/post/repository/PostRepository.java
  src/main/java/org/programmers/springboardjpa/domain/post/service/PostConverter.java
  src/main/java/org/programmers/springboardjpa/domain/post/service/PostDefaultService.java
  src/main/java/org/programmers/springboardjpa/domain/post/service/PostService.java
  src/main/java/org/programmers/springboardjpa/domain/user/domain/User.java
  src/main/java/org/programmers/springboardjpa/domain/user/dto/UserDto.java
  src/main/java/org/programmers/springboardjpa/global/config/JpaAuditingConfig.java
  src/main/java/org/programmers/springboardjpa/global/config/MvcConfig.java
  src/main/java/org/programmers/springboardjpa/global/error/ErrorResponse.java
  src/main/java/org/programmers/springboardjpa/global/error/GlobalExceptionHandler.java
  src/main/java/org/programmers/springboardjpa/global/error/exception/BusinessException.java
  src/main/java/org/programmers/springboardjpa/global/error/exception/ErrorCode.java
  src/main/resources/application.yaml
  src/main/resources/logback.xml
  src/test/java/org/programmers/springboardjpa/post/controller/PostApiTest.java
  src/test/java/org/programmers/springboardjpa/post/service/PostDefaultServiceStubTest.java
  src/test/java/org/programmers/springboardjpa/post/service/PostDefaultServiceTest.java
Labels: Team-R, 🔥 매운맛

#151 [2기-P 이연우 ] Spring Boot JPA 게시판 구현 코드 리뷰 부탁드립니다
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/api-doc.adoc
  src/main/java/com/prgrms/boardjpa/BoardJpaApplication.java
  src/main/java/com/prgrms/boardjpa/application/post/PostConverter.java
  src/main/java/com/prgrms/boardjpa/application/post/PostDto.java
  src/main/java/com/prgrms/boardjpa/application/post/controller/PostRestController.java
  src/main/java/com/prgrms/boardjpa/application/post/exception/LikeOwnPostException.java
  src/main/java/com/prgrms/boardjpa/application/post/model/Post.java
  src/main/java/com/prgrms/boardjpa/application/post/model/PostLike.java
  src/main/java/com/prgrms/boardjpa/application/post/repository/PostLikeRepository.java
  src/main/java/com/prgrms/boardjpa/application/post/repository/PostRepository.java
  src/main/java/com/prgrms/boardjpa/application/post/service/PostService.java
  src/main/java/com/prgrms/boardjpa/application/user/UserConverter.java
  src/main/java/com/prgrms/boardjpa/application/user/UserDto.java
  src/main/java/com/prgrms/boardjpa/application/user/controller/UserRestController.java
  src/main/java/com/prgrms/boardjpa/application/user/exception/AuthenticationFailException.java
  src/main/java/com/prgrms/boardjpa/application/user/exception/AuthorizationFailException.java
  src/main/java/com/prgrms/boardjpa/application/user/model/Hobby.java
  src/main/java/com/prgrms/boardjpa/application/user/model/User.java
  src/main/java/com/prgrms/boardjpa/application/user/repository/UserRepository.java
  src/main/java/com/prgrms/boardjpa/application/user/service/UserService.java
  src/main/java/com/prgrms/boardjpa/core/commons/api/BindingErrorResponse.java
  src/main/java/com/prgrms/boardjpa/core/commons/api/ErrorResponse.java
  src/main/java/com/prgrms/boardjpa/core/commons/api/GlobalExceptionHandler.java
  src/main/java/com/prgrms/boardjpa/core/commons/api/SuccessResponse.java
  src/main/java/com/prgrms/boardjpa/core/commons/domain/BaseEntity.java
  src/main/java/com/prgrms/boardjpa/core/commons/exception/CreationFailException.java
  src/main/java/com/prgrms/boardjpa/core/commons/exception/NotExistException.java
  src/main/java/com/prgrms/boardjpa/core/commons/page/SimplePage.java
  src/main/java/com/prgrms/boardjpa/core/config/JpaAuditingConfig.java
  src/main/resources/application.yml
  src/test/java/com/prgrms/boardjpa/application/post/PostTest.java
  src/test/java/com/prgrms/boardjpa/application/post/controller/PostRestControllerTest.java
  src/test/java/com/prgrms/boardjpa/application/post/repository/PostRepositoryTest.java
  src/test/java/com/prgrms/boardjpa/application/post/service/PostLikeServiceTest.java
  src/test/resources/application.yml
Labels: Team-R, 💧 순한맛

#146 [2기-P] 마지영 SpringBoot Board JPA 미션 제출합니다
  springboot-board-jpa/.gitignore
  springboot-board-jpa/.mvn/wrapper/maven-wrapper.jar
  springboot-board-jpa/.mvn/wrapper/maven-wrapper.properties
  springboot-board-jpa/docs/asciidocs/get-all-posts-with-page.adoc
  springboot-board-jpa/docs/asciidocs/get-all-posts.adoc
  springboot-board-jpa/docs/asciidocs/get-all-users-with-page.adoc
  springboot-board-jpa/docs/asciidocs/get-all-users.adoc
  springboot-board-jpa/docs/asciidocs/index.adoc
  springboot-board-jpa/docs/asciidocs/index.html
  springboot-board-jpa/docs/asciidocs/post-save.adoc
  springboot-board-jpa/docs/asciidocs/post-update.adoc
  springboot-board-jpa/docs/asciidocs/user-save.adoc
  springboot-board-jpa/mvnw
  springboot-board-jpa/mvnw.cmd
  springboot-board-jpa/pom.xml
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/BaseEntity.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/Patterns.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/SpringbootBoardJpaApplication.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/exception/controller/ExceptionRestControllerAdvice.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/exception/exceptions/CustomExceptionCode.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/exception/exceptions/CustomRuntimeException.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/exception/response/ErrorResponse.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/post/controller/PostRestController.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/post/dto/PostConverter.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/post/dto/PostDto.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/post/dto/PostResponse.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/post/entity/Post.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/post/repository/PostRepository.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/post/service/PostService.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/user/controller/UserRestController.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/user/dto/UserDto.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/user/dto/UserResponse.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/user/entity/Name.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/user/entity/User.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/user/repository/UserRepository.java
  springboot-board-jpa/src/main/java/com/prgrms/springbootboardjpa/user/service/UserService.java
  springboot-board-jpa/src/main/resources/application.yml
  springboot-board-jpa/src/test/java/com/prgrms/springbootboardjpa/post/controller/PostRestControllerTest.java
  springboot-board-jpa/src/test/java/com/prgrms/springbootboardjpa/post/service/PostServiceTest.java
  springboot-board-jpa/src/test/java/com/prgrms/springbootboardjpa/user/controller/UserRestControllerTest.java
  springboot-board-jpa/src/test/java/com/prgrms/springbootboardjpa/user/repository/UserRepositoryTest.java
  springboot-board-jpa/src/test/java/com/prgrms/springbootboardjpa/user/service/UserServiceTest.java
Labels: Team-R, 💧 순한맛

#149 [2기-P 김진욱] Springboot JPA 게시판 작성 과제입니다.
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  HELP.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/programmers/board/BoardApplication.java
  src/main/java/com/programmers/board/controller/ApiResponse.java
  src/main/java/com/programmers/board/controller/PostController.java
  src/main/java/com/programmers/board/controller/UserController.java
  src/main/java/com/programmers/board/dto/Convertor.java
  src/main/java/com/programmers/board/dto/PostRequestDto.java
  src/main/java/com/programmers/board/dto/PostResponseDto.java
  src/main/java/com/programmers/board/dto/UserRequestDto.java
  src/main/java/com/programmers/board/entity/CreatedInfo.java
  src/main/java/com/programmers/board/entity/Post.java
  src/main/java/com/programmers/board/entity/User.java
  src/main/java/com/programmers/board/exception/NotFoundException.java
  src/main/java/com/programmers/board/repository/PostRepository.java
  src/main/java/com/programmers/board/repository/UserRepository.java
  src/main/java/com/programmers/board/service/PostService.java
  src/main/java/com/programmers/board/service/UserService.java
  src/main/resources/application.yml
  src/test/java/com/programmers/board/service/PostServiceTest.java
Labels: Team-R, 💧 순한맛
