Repository prgrms-be-devcourse/springboot-board-jpa, pull requests merged in 2023-01, with the labels that each got.

#171 [3기-C 권성준] JPA 게시판 과제 제출합니다.
  .gitignore
  README.md
  build.gradle
  settings.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/main/java/com/programmers/jpaboard/JpaBoardApplication.java
  src/main/java/com/programmers/jpaboard/common/exception/PostNotFoundException.java
  src/main/java/com/programmers/jpaboard/common/exception/UserNotFoundException.java
  src/main/java/com/programmers/jpaboard/domain/BaseEntity.java
  src/main/java/com/programmers/jpaboard/domain/post/dto/PostCreateRequestDto.java
  src/main/java/com/programmers/jpaboard/domain/post/dto/PostResponseDto.java
  src/main/java/com/programmers/jpaboard/domain/post/dto/PostResponseDtoList.java
  src/main/java/com/programmers/jpaboard/domain/post/dto/PostUpdateRequestDto.java
  src/main/java/com/programmers/jpaboard/domain/post/entity/Post.java
  src/main/java/com/programmers/jpaboard/domain/post/repository/PostRepository.java
  src/main/java/com/programmers/jpaboard/domain/post/service/PostService.java
  src/main/java/com/programmers/jpaboard/domain/post/util/PostConverter.java
  src/main/java/com/programmers/jpaboard/domain/user/dto/UserCreateRequestDto.java
  src/main/java/com/programmers/jpaboard/domain/user/dto/UserResponseDto.java
  src/main/java/com/programmers/jpaboard/domain/user/entity/User.java
  src/main/java/com/programmers/jpaboard/domain/user/repository/UserRepository.java
  src/main/java/com/programmers/jpaboard/domain/user/service/UserService.java
  src/main/java/com/programmers/jpaboard/domain/user/util/UserConverter.java
  src/main/java/com/programmers/jpaboard/web/common/ExceptionResult.java
  src/main/java/com/programmers/jpaboard/web/common/GlobalControllerAdvice.java
  src/main/java/com/programmers/jpaboard/web/post/PostApiController.java
  src/main/java/com/programmers/jpaboard/web/user/UserApiController.java
  src/main/resources/application.yml
  src/test/java/com/programmers/jpaboard/common/util/PostConverterTest.java
  src/test/java/com/programmers/jpaboard/domain/post/entity/PostTest.java
  src/test/java/com/programmers/jpaboard/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/programmers/jpaboard/domain/post/service/PostServiceTest.java
  src/test/java/com/programmers/jpaboard/domain/user/entity/UserTest.java
  src/test/java/com/programmers/jpaboard/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/programmers/jpaboard/web/post/PostApiControllerTest.java
  src/test/java/com/programmers/jpaboard/web/user/UserApiControllerTest.java
Labels: 🔥 매운맛, Team-Marco

#190 [3기-C 장영지] JPA 게시판 구현 미션
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/example/springbootboardjpa/SpringbootBoardJpaApplication.java
  src/main/java/com/example/springbootboardjpa/controller/ApiResponse.java
  src/main/java/com/example/springbootboardjpa/controller/PostController.java
  src/main/java/com/example/springbootboardjpa/controller/PostExceptionHandler.java
  src/main/java/com/example/springbootboardjpa/converter/PostConverter.java
  src/main/java/com/example/springbootboardjpa/dto/PostDTO.java
  src/main/java/com/example/springbootboardjpa/dto/UserDto.java
  src/main/java/com/example/springbootboardjpa/exception/NotFoundException.java
  src/main/java/com/example/springbootboardjpa/model/BaseEntity.java
  src/main/java/com/example/springbootboardjpa/model/Post.java
  src/main/java/com/example/springbootboardjpa/model/TimeBaseEntity.java
  src/main/java/com/example/springbootboardjpa/model/User.java
  src/main/java/com/example/springbootboardjpa/repoistory/PostJpaRepository.java
  src/main/java/com/example/springbootboardjpa/repoistory/UserJpaRepository.java
  src/main/java/com/example/springbootboardjpa/service/DefaultPostService.java
  src/main/java/com/example/springbootboardjpa/service/PostService.java
  src/main/resources/application.yaml
  src/test/java/com/example/springbootboardjpa/SpringbootBoardJpaApplicationTests.java
  src/test/java/com/example/springbootboardjpa/controller/PostControllerTest.java
  src/test/java/com/example/springbootboardjpa/model/PostTest.java
  src/test/java/com/example/springbootboardjpa/model/UserTest.java
  src/test/java/com/example/springbootboardjpa/repoistory/PostJpaRepositoryTest.java
  src/test/java/com/example/springbootboardjpa/repoistory/UserJpaRepositoryTest.java
  src/test/java/com/example/springbootboardjpa/service/DefaultPostServiceTest.java
Labels: 🔥 매운맛, Team-Blackdog

#194 [3기-C 이수린] 앨런팀 게시판 추가 미션 제출합니다.
  src/main/java/com/spring/board/springboard/domain/ErrorResponse.java
  src/main/java/com/spring/board/springboard/domain/GlobalExceptionHandler.java
  src/main/java/com/spring/board/springboard/domain/Response.java
  src/main/java/com/spring/board/springboard/domain/ValidationErrorResponse.java
  src/main/java/com/spring/board/springboard/post/controller/PostController.java
  src/main/java/com/spring/board/springboard/post/domain/Post.java
  src/main/java/com/spring/board/springboard/post/domain/dto/PostCreateRequestDto.java
  src/main/java/com/spring/board/springboard/post/domain/dto/PostDetailResponseDto.java
  src/main/java/com/spring/board/springboard/post/domain/dto/PostSummaryResponseDto.java
  src/main/java/com/spring/board/springboard/post/domain/dto/RequestPostDto.java
  src/main/java/com/spring/board/springboard/post/domain/dto/ResponsePostDto.java
  src/main/java/com/spring/board/springboard/post/service/PostService.java
  src/main/java/com/spring/board/springboard/user/MemberExceptionHandler.java
  src/main/java/com/spring/board/springboard/user/controller/CookieUtils.java
  src/main/java/com/spring/board/springboard/user/controller/MemberController.java
  src/main/java/com/spring/board/springboard/user/domain/Member.java
  src/main/java/com/spring/board/springboard/user/domain/MemberDto.java
  src/main/java/com/spring/board/springboard/user/domain/MemberResponseDto.java
  src/main/java/com/spring/board/springboard/user/domain/dto/MemberDetailResponseDto.java
  src/main/java/com/spring/board/springboard/user/domain/dto/MemberLoginDto.java
  src/main/java/com/spring/board/springboard/user/domain/dto/MemberRequestDto.java
  src/main/java/com/spring/board/springboard/user/domain/dto/MemberSummaryResponseDto.java
  src/main/java/com/spring/board/springboard/user/domain/validation/EmailValidator.java
  src/main/java/com/spring/board/springboard/user/exception/AuthenticateException.java
  src/main/java/com/spring/board/springboard/user/repository/MemberRepository.java
  src/main/java/com/spring/board/springboard/user/service/MemberService.java
  src/main/resources/static/docs/api.html
  src/test/java/com/spring/board/springboard/post/controller/PostControllerTest.java
  src/test/java/com/spring/board/springboard/post/repository/PostRepositoryTest.java
  src/test/java/com/spring/board/springboard/post/service/PostServiceTest.java
  src/test/java/com/spring/board/springboard/user/domain/MemberTest.java
  src/test/java/com/spring/board/springboard/user/service/MemberServiceTest.java
  src/test/resources/application.yml
Labels: Team-Allen, 🔥 매운맛

#197 [3기-C 김환] 앨런팀 게시판 추가 미션 제출합니다
  build.gradle
  src/main/java/com/example/board/common/exception/UnAuthorizedException.java
  src/main/java/com/example/board/common/util/AuthorityUtils.java
  src/main/java/com/example/board/domain/member/controller/MemberController.java
  src/main/java/com/example/board/domain/member/dto/MemberRequest.java
  src/main/java/com/example/board/domain/member/dto/MemberResponse.java
  src/main/java/com/example/board/domain/member/entity/Member.java
  src/main/java/com/example/board/domain/member/repository/MemberRepository.java
  src/main/java/com/example/board/domain/member/service/MemberService.java
  src/main/java/com/example/board/domain/post/dto/PostRequest.java
  src/main/java/com/example/board/domain/post/dto/PostResponse.java
  src/main/java/com/example/board/domain/post/entity/Post.java
  src/main/java/com/example/board/domain/post/service/PostService.java
  src/main/resources/application.yml
  src/test/java/com/example/board/domain/member/controller/MemberControllerTest.java
  src/test/java/com/example/board/domain/member/entity/MemberTest.java
  src/test/java/com/example/board/domain/member/entity/MemberValidationTest.java
  src/test/java/com/example/board/domain/post/controller/PostControllerTest.java
  src/test/java/com/example/board/domain/post/entity/PostTest.java
Labels: Team-Allen, 🔥 매운맛

#196 [3기-C 서예원] 앨런팀 게시판 추가 미션 제출합니다
  build.gradle
  src/main/java/com/prgrms/domain/post/Post.java
  src/main/java/com/prgrms/domain/post/PostController.java
  src/main/java/com/prgrms/domain/user/Regex.java
  src/main/java/com/prgrms/domain/user/User.java
  src/main/java/com/prgrms/domain/user/UserController.java
  src/main/java/com/prgrms/domain/user/UserRepository.java
  src/main/java/com/prgrms/domain/user/UserService.java
  src/main/java/com/prgrms/dto/UserDto.java
  src/main/java/com/prgrms/exception/ErrorCode.java
  src/main/java/com/prgrms/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/exception/customException/AuthenticationFailedException.java
  src/main/java/com/prgrms/exception/customException/CustomException.java
  src/main/java/com/prgrms/exception/customException/EmailDuplicateException.java
  src/main/java/com/prgrms/exception/customException/LoginFailException.java
  src/main/java/com/prgrms/exception/customException/PostNotFoundException.java
  src/main/java/com/prgrms/exception/customException/UserNotFoundException.java
  src/main/java/com/prgrms/web/api/UserController.java
  src/main/java/com/prgrms/web/auth/CookieUtil.java
  src/test/java/com/prgrms/domain/post/PostControllerTest.java
  src/test/java/com/prgrms/domain/user/UserServiceTest.java
Labels: Team-Allen, 🔥 매운맛

#177 [3기-C 복신영] JPA 게시판 구현 미션 제출합니다
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/kdt/springbootboardjpa/SpringbootBoardJpaApplication.java
  src/main/java/kdt/springbootboardjpa/controller/PostController.java
  src/main/java/kdt/springbootboardjpa/controller/request/SavePostRequest.java
  src/main/java/kdt/springbootboardjpa/controller/response/PostResponse.java
  src/main/java/kdt/springbootboardjpa/global/dto/ApiError.java
  src/main/java/kdt/springbootboardjpa/global/dto/BaseResponse.java
  src/main/java/kdt/springbootboardjpa/global/entity/BaseEntity.java
  src/main/java/kdt/springbootboardjpa/global/exception/ExceptionResolver.java
  src/main/java/kdt/springbootboardjpa/global/utils/ResponseUtil.java
  src/main/java/kdt/springbootboardjpa/respository/PostRepository.java
  src/main/java/kdt/springbootboardjpa/respository/UserRepository.java
  src/main/java/kdt/springbootboardjpa/respository/entity/Post.java
  src/main/java/kdt/springbootboardjpa/respository/entity/User.java
  src/main/java/kdt/springbootboardjpa/service/PostService.java
  src/main/java/kdt/springbootboardjpa/service/dto/PostDto.java
  src/main/resources/application.yml
  src/main/resources/static/docs/api.html
  src/test/java/kdt/springbootboardjpa/SpringbootBoardJpaApplicationTests.java
  src/test/java/kdt/springbootboardjpa/controller/PostControllerTest.java
  src/test/java/kdt/springbootboardjpa/repository/PostRepositoryTest.java
  src/test/java/kdt/springbootboardjpa/service/PostDtoTest.java
  src/test/java/kdt/springbootboardjpa/service/PostServiceTest.java
Labels: Team-R

#184 [3기-C 이수영] JPA 게시판 과제 제출합니다.
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  README.md
  erd.png
  images/erd.png
  images/post_create.png
  images/post_find_all_1.png
  images/post_find_all_2.png
  images/post_find_one.png
  images/post_update.png
  pom.xml
  src/main/asciidoc/index.adoc
  src/main/java/com/prgrms/be/app/JpaNoticeBoardApplication.java
  src/main/java/com/prgrms/be/app/config/JpaConfig.java
  src/main/java/com/prgrms/be/app/controller/ControllerExceptionHandler.java
  src/main/java/com/prgrms/be/app/controller/PostController.java
  src/main/java/com/prgrms/be/app/controller/ResponseMessage.java
  src/main/java/com/prgrms/be/app/domain/BaseEntity.java
  src/main/java/com/prgrms/be/app/domain/Post.java
  src/main/java/com/prgrms/be/app/domain/User.java
  src/main/java/com/prgrms/be/app/domain/dto/ApiResponse.java
  src/main/java/com/prgrms/be/app/domain/dto/PostCreateRequest.java
  src/main/java/com/prgrms/be/app/domain/dto/PostDetailResponse.java
  src/main/java/com/prgrms/be/app/domain/dto/PostPageRequest.java
  src/main/java/com/prgrms/be/app/domain/dto/PostUpdateRequest.java
  src/main/java/com/prgrms/be/app/domain/dto/PostsResponse.java
  src/main/java/com/prgrms/be/app/repository/PostRepository.java
  src/main/java/com/prgrms/be/app/repository/UserRepository.java
  src/main/java/com/prgrms/be/app/service/PostService.java
  src/main/java/com/prgrms/be/app/util/PostConverter.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/static/index.html
  src/test/java/com/prgrms/be/app/controller/PostControllerTest.java
  src/test/java/com/prgrms/be/app/domain/PostTest.java
  src/test/java/com/prgrms/be/app/domain/UserTest.java
  src/test/java/com/prgrms/be/app/domain/dto/PostDTOTest.java
  src/test/java/com/prgrms/be/app/service/PostServiceTest.java
Labels: 💧 순한맛, 🔥 매운맛, Team-Marco

#211 [3기-C 장주영] JPA 게시판 구현 미션 제출합니다
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/example/springbootboardjpa/SpringbootBoardJpaApplication.java
  src/main/java/com/example/springbootboardjpa/domain/member/controller/MemberController.java
  src/main/java/com/example/springbootboardjpa/domain/member/entity/Member.java
  src/main/java/com/example/springbootboardjpa/domain/member/repository/MemberRepository.java
  src/main/java/com/example/springbootboardjpa/domain/post/contorller/PostController.java
  src/main/java/com/example/springbootboardjpa/domain/post/dto/request/PostSaveRequestDto.java
  src/main/java/com/example/springbootboardjpa/domain/post/dto/request/PostUpdateRequestDto.java
  src/main/java/com/example/springbootboardjpa/domain/post/dto/response/PostFindAllResponseDto.java
  src/main/java/com/example/springbootboardjpa/domain/post/dto/response/PostFindByIdResponseDto.java
  src/main/java/com/example/springbootboardjpa/domain/post/dto/response/PostSaveResponseDto.java
  src/main/java/com/example/springbootboardjpa/domain/post/dto/response/PostUpdateResponseDto.java
  src/main/java/com/example/springbootboardjpa/domain/post/entity/Post.java
  src/main/java/com/example/springbootboardjpa/domain/post/repository/PostRepository.java
  src/main/java/com/example/springbootboardjpa/domain/post/service/PostService.java
  src/main/java/com/example/springbootboardjpa/global/aop/CommonPointcut.java
  src/main/java/com/example/springbootboardjpa/global/aop/LogAspect.java
  src/main/java/com/example/springbootboardjpa/global/entity/BaseTimeEntity.java
  src/main/java/com/example/springbootboardjpa/global/exception/CustomException.java
  src/main/java/com/example/springbootboardjpa/global/exception/ErrorCode.java
  src/main/java/com/example/springbootboardjpa/global/exception/ErrorResponse.java
  src/main/java/com/example/springbootboardjpa/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/main/resources/static/docs/index.html
  src/test/java/com/example/springbootboardjpa/SpringbootBoardJpaApplicationTests.java
  src/test/java/com/example/springbootboardjpa/domain/post/contorller/PostControllerTest.java
  src/test/java/com/example/springbootboardjpa/domain/post/service/PostServiceTest.java
Labels: 🔥 매운맛, Team-F
