Repository prgrms-be-devcourse/springboot-board-jpa, pull requests merged in 2023-08, with the labels that each got.

#222 [4기 김범우 최성원] - JPA 게시판 미션 엔티티 설계
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/board/BoardApplication.java
  src/main/java/com/kdt/board/domain/post/entity/Post.java
  src/main/java/com/kdt/board/domain/user/entity/User.java
  src/main/java/com/kdt/board/global/entity/BaseEntity.java
  src/main/resources/application.yml
Labels: 🔥 매운맛, Team-Ray

#226 [4기 김범우 최성원] - User, Post 엔티티 연관관계 설정, repository 생성
  src/main/java/com/kdt/board/domain/post/entity/Post.java
  src/main/java/com/kdt/board/domain/post/repository/PostRepository.java
  src/main/java/com/kdt/board/domain/user/entity/User.java
  src/main/java/com/kdt/board/domain/user/repository/UserRepository.java
Labels: 🔥 매운맛, Team-Ray

#221 [4기] 주홍석, 황준호 프로젝트 세팅 및 엔티티 생성
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/ray/springbootboard/SpringbootBoardApplication.java
  src/main/java/com/ray/springbootboard/config/JPAConfig.java
  src/main/java/com/ray/springbootboard/domain/BaseTimeEntity.java
  src/main/java/com/ray/springbootboard/domain/Post.java
  src/main/java/com/ray/springbootboard/domain/User.java
  src/main/resources/application.yml
Labels: 🔥 매운맛, Team-Ray

#237 [4기] 주홍석 황준호 레포지토리, 서비스 구조 생성
  src/main/java/com/ray/springbootboard/repository/PostRepository.java
  src/main/java/com/ray/springbootboard/repository/UserRepository.java
  src/main/java/com/ray/springbootboard/service/PostService.java
  src/main/java/com/ray/springbootboard/service/UserService.java
  src/main/java/com/ray/springbootboard/service/vo/PostUpdateInfo.java
Labels: 🔥 매운맛, Team-Ray

#217 [4기 박현지, 최지연] 프로젝트 세팅 및 엔티티 생성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/prgms/boardservice/BoardServiceApplication.java
  src/main/java/org/prgms/boardservice/domain/BaseTime.java
  src/main/java/org/prgms/boardservice/domain/post/Post.java
  src/main/java/org/prgms/boardservice/domain/user/User.java
Labels: 🔥 매운맛, Team-Ray

#232 [4기 문희조] Spring Boot JPA 게시판 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/kdt/devcourse/SpringJpaBoardApplication.java
  src/main/java/com/kdt/devcourse/global/ApiResponse.java
  src/main/java/com/kdt/devcourse/global/BaseEntity.java
  src/main/java/com/kdt/devcourse/global/exception/ErrorCode.java
  src/main/java/com/kdt/devcourse/global/exception/ErrorResponse.java
  src/main/java/com/kdt/devcourse/global/exception/GlobalExceptionHandler.java
  src/main/java/com/kdt/devcourse/module/post/application/PostService.java
  src/main/java/com/kdt/devcourse/module/post/domain/Post.java
  src/main/java/com/kdt/devcourse/module/post/domain/repository/PostRepository.java
  src/main/java/com/kdt/devcourse/module/post/presentation/PostController.java
  src/main/java/com/kdt/devcourse/module/post/presentation/dto/CreateOrUpdatePost.java
  src/main/java/com/kdt/devcourse/module/user/domain/User.java
  src/main/java/com/kdt/devcourse/module/user/domain/repository/UserRepository.java
  src/main/resources/application.yml
  src/test/java/com/kdt/devcourse/module/post/application/PostServiceTest.java
  src/test/java/com/kdt/devcourse/module/post/domain/repository/PostRepositoryTest.java
  src/test/java/com/kdt/devcourse/module/post/presentation/PostControllerTest.java
  src/test/resources/application.yml
Labels: 🔥 매운맛, Team-Kyu

#212 [4기 김범석, 박형진] Spring Boot JPA로 게시판 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/myadoc.adoc
  src/main/java/com/example/springbootjpa/SpringbootJpaApplication.java
  src/main/java/com/example/springbootjpa/application/PostService.java
  src/main/java/com/example/springbootjpa/application/UserService.java
  src/main/java/com/example/springbootjpa/configuration/AuditingConfiguration.java
  src/main/java/com/example/springbootjpa/domain/BaseEntity.java
  src/main/java/com/example/springbootjpa/domain/post/Post.java
  src/main/java/com/example/springbootjpa/domain/post/PostRepository.java
  src/main/java/com/example/springbootjpa/domain/user/Hobby.java
  src/main/java/com/example/springbootjpa/domain/user/User.java
  src/main/java/com/example/springbootjpa/domain/user/UserRepository.java
  src/main/java/com/example/springbootjpa/ui/PostController.java
  src/main/java/com/example/springbootjpa/ui/UserController.java
  src/main/java/com/example/springbootjpa/ui/dto/post/PostFindResponse.java
  src/main/java/com/example/springbootjpa/ui/dto/post/PostSaveRequest.java
  src/main/java/com/example/springbootjpa/ui/dto/post/PostSaveResponse.java
  src/main/java/com/example/springbootjpa/ui/dto/post/PostUpdateRequest.java
  src/main/java/com/example/springbootjpa/ui/dto/post/PostUpdateResponse.java
  src/main/java/com/example/springbootjpa/ui/dto/user/UserFindResponse.java
  src/main/java/com/example/springbootjpa/ui/dto/user/UserSaveRequest.java
  src/main/java/com/example/springbootjpa/ui/dto/user/UserSaveResponse.java
  src/main/resources/application.yaml
  src/main/resources/static/docs/myadoc.html
  src/test/java/com/example/springbootjpa/SpringbootJpaApplicationTests.java
  src/test/java/com/example/springbootjpa/ui/PostControllerTest.java
  src/test/java/com/example/springbootjpa/ui/UserControllerTest.java
Labels: Team-Allen

#239 [4기] 주홍석 황준호 - Post Controller 기능 구현
  src/main/java/com/ray/springbootboard/controller/PostController.java
  src/main/java/com/ray/springbootboard/controller/dto/PageResponse.java
  src/main/java/com/ray/springbootboard/controller/dto/PostResponse.java
  src/main/java/com/ray/springbootboard/controller/dto/PostSaveRequest.java
  src/main/java/com/ray/springbootboard/controller/dto/PostUpdateRequest.java
  src/main/java/com/ray/springbootboard/domain/Post.java
  src/test/java/com/ray/springbootboard/controller/PostControllerTest.java
Labels: 🔥 매운맛, Team-Ray

#236 [4기 김범우 최성원] - PostService, PostController 작성
  src/main/java/com/kdt/board/domain/post/controller/PostController.java
  src/main/java/com/kdt/board/domain/post/dto/PostCreateRequestDto.java
  src/main/java/com/kdt/board/domain/post/dto/PostResponseDto.java
  src/main/java/com/kdt/board/domain/post/dto/PostUpdateRequestDto.java
  src/main/java/com/kdt/board/domain/post/entity/Post.java
  src/main/java/com/kdt/board/domain/post/service/PostService.java
  src/main/java/com/kdt/board/domain/user/entity/User.java
  src/main/java/com/kdt/board/domain/user/service/UserService.java
  src/main/java/com/kdt/board/global/entity/BaseEntity.java
  src/main/java/com/kdt/board/global/exception/BaseException.java
  src/main/resources/application.yml
Labels: 🔥 매운맛, Team-Ray

#249 [4기 박현지, 최지연] 엔티티 테스트, 서비스 코드 구현 및 테스트
  build.gradle
  src/main/java/org/prgms/boardservice/config/JpaConfiguration.java
  src/main/java/org/prgms/boardservice/domain/BaseTime.java
  src/main/java/org/prgms/boardservice/domain/post/Post.java
  src/main/java/org/prgms/boardservice/domain/post/PostRepository.java
  src/main/java/org/prgms/boardservice/domain/post/PostService.java
  src/main/java/org/prgms/boardservice/domain/post/vo/PostUpdateVo.java
  src/main/java/org/prgms/boardservice/domain/user/User.java
  src/main/java/org/prgms/boardservice/domain/user/UserRepository.java
  src/main/java/org/prgms/boardservice/domain/user/UserService.java
  src/main/java/org/prgms/boardservice/util/ErrorMessage.java
  src/test/java/org/prgms/boardservice/domain/post/PostServiceTest.java
  src/test/java/org/prgms/boardservice/domain/post/PostTest.java
  src/test/java/org/prgms/boardservice/domain/user/UserServiceTest.java
  src/test/java/org/prgms/boardservice/domain/user/UserTest.java
Labels: 🔥 매운맛, Team-Ray

#260 [4기] 주홍석, 황준호 서비스 레이어 구현 및 테스트 작성
  src/main/java/com/ray/springbootboard/controller/PostController.java
  src/main/java/com/ray/springbootboard/controller/dto/PostSaveRequest.java
  src/main/java/com/ray/springbootboard/domain/Post.java
  src/main/java/com/ray/springbootboard/domain/User.java
  src/main/java/com/ray/springbootboard/service/PostService.java
  src/main/java/com/ray/springbootboard/service/PostServiceImpl.java
  src/main/java/com/ray/springbootboard/service/UserService.java
  src/main/java/com/ray/springbootboard/service/UserServiceImpl.java
  src/test/java/com/ray/springbootboard/controller/PostControllerTest.java
  src/test/java/com/ray/springbootboard/service/PostServiceTest.java
Labels: 🔥 매운맛, Team-Ray

#233 [4기 김주웅] Spring Boot JPA 게시판 구현 미션 제출합니다
  .gitignore
  README.md
  build.gradle
  doc/README_OLD.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/juwoong/springbootboardjpa/SpringbootBoardJpaApplication.java
  src/main/java/com/juwoong/springbootboardjpa/common/BaseEntity.java
  src/main/java/com/juwoong/springbootboardjpa/post/api/PostController.java
  src/main/java/com/juwoong/springbootboardjpa/post/api/model/PostRequest.java
  src/main/java/com/juwoong/springbootboardjpa/post/application/PostService.java
  src/main/java/com/juwoong/springbootboardjpa/post/application/model/PostDto.java
  src/main/java/com/juwoong/springbootboardjpa/post/domain/Post.java
  src/main/java/com/juwoong/springbootboardjpa/post/domain/repository/PostRepository.java
  src/main/java/com/juwoong/springbootboardjpa/user/api/UserController.java
  src/main/java/com/juwoong/springbootboardjpa/user/api/model/UserRequest.java
  src/main/java/com/juwoong/springbootboardjpa/user/application/UserProvider.java
  src/main/java/com/juwoong/springbootboardjpa/user/application/UserService.java
  src/main/java/com/juwoong/springbootboardjpa/user/application/model/UserDto.java
  src/main/java/com/juwoong/springbootboardjpa/user/domain/User.java
  src/main/java/com/juwoong/springbootboardjpa/user/domain/constant/Hobby.java
  src/main/java/com/juwoong/springbootboardjpa/user/domain/repository/UserRepository.java
  src/main/resources/application.yml
  src/test/java/com/juwoong/springbootboardjpa/post/api/PostControllerTest.java
  src/test/java/com/juwoong/springbootboardjpa/post/domain/PostRepositoryTest.java
  src/test/java/com/juwoong/springbootboardjpa/user/api/UserControllerTest.java
  src/test/java/com/juwoong/springbootboardjpa/user/domain/repository/UserRepositoryTest.java
Labels: 🔥 매운맛, Team-Kyu

#227 [4기 김도연, 한희나] Spring Boot JPA로 게시판 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/api/post/create.adoc
  src/docs/asciidoc/api/post/find-all.adoc
  src/docs/asciidoc/api/post/find-one.adoc
  src/docs/asciidoc/api/post/update.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/org/prgms/springbootBoardJpa/SpringbootBoardJpaApplication.java
  src/main/java/org/prgms/springbootBoardJpa/controller/PostController.java
  src/main/java/org/prgms/springbootBoardJpa/domain/BaseEntity.java
  src/main/java/org/prgms/springbootBoardJpa/domain/Post.java
  src/main/java/org/prgms/springbootBoardJpa/domain/PostRepository.java
  src/main/java/org/prgms/springbootBoardJpa/domain/User.java
  src/main/java/org/prgms/springbootBoardJpa/service/PostCreateRequest.java
  src/main/java/org/prgms/springbootBoardJpa/service/PostResponse.java
  src/main/java/org/prgms/springbootBoardJpa/service/PostService.java
  src/main/java/org/prgms/springbootBoardJpa/service/PostUpdateRequest.java
  src/main/java/org/prgms/springbootBoardJpa/service/UserInfo.java
  src/main/resources/application.yml
  src/test/java/org/prgms/springbootBoardJpa/controller/PostControllerTest.java
  src/test/java/org/prgms/springbootBoardJpa/controller/RestDocsSupport.java
Labels: Team-Allen, 🔥 매운맛

#216 [4기 오세한] Spring Boot JPA 게시판 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/index.html
  src/main/java/prgms/boardmission/ApiResponse.java
  src/main/java/prgms/boardmission/BoardMissionApplication.java
  src/main/java/prgms/boardmission/domain/BaseEntity.java
  src/main/java/prgms/boardmission/domain/Member.java
  src/main/java/prgms/boardmission/domain/Post.java
  src/main/java/prgms/boardmission/member/MemberConverter.java
  src/main/java/prgms/boardmission/member/dto/MemberDto.java
  src/main/java/prgms/boardmission/post/PostConverter.java
  src/main/java/prgms/boardmission/post/controller/PostController.java
  src/main/java/prgms/boardmission/post/dto/PostDto.java
  src/main/java/prgms/boardmission/post/dto/PostUpdateDto.java
  src/main/java/prgms/boardmission/post/exception/NotFoundPostException.java
  src/main/java/prgms/boardmission/post/repository/PostRepository.java
  src/main/java/prgms/boardmission/post/service/PostService.java
  src/main/resources/application.properties
  src/test/java/prgms/boardmission/BoardMissionApplicationTests.java
  src/test/java/prgms/boardmission/post/controller/PostControllerTest.java
  src/test/java/prgms/boardmission/post/service/PostServiceTest.java
  src/test/resources/application.properties
Labels: 🔥 매운맛, Team-Kyu

#241 [4기 김예슬] Spring Boot JPA 게시판 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/programmers/jpaBoard/JpaBoardApplication.java
  src/main/java/programmers/jpaBoard/api/PostController.java
  src/main/java/programmers/jpaBoard/dto/CreatedPost.java
  src/main/java/programmers/jpaBoard/dto/PostResponse.java
  src/main/java/programmers/jpaBoard/dto/UpdatedPost.java
  src/main/java/programmers/jpaBoard/entity/BaseEntity.java
  src/main/java/programmers/jpaBoard/entity/Post.java
  src/main/java/programmers/jpaBoard/entity/User.java
  src/main/java/programmers/jpaBoard/exception/ErrorMessage.java
  src/main/java/programmers/jpaBoard/repository/PostRepository.java
  src/main/java/programmers/jpaBoard/service/PostService.java
  src/main/resources/application.yml
  src/test/java/programmers/jpaBoard/api/PostControllerTest.java
  src/test/java/programmers/jpaBoard/service/PostServiceTest.java
Labels: 🔥 매운맛, Team-Kyu

#262 [4기] 주홍석, 황준호 Rest Docs 적용
  build.gradle
  src/docs/asciidoc/index.adoc
  src/test/java/com/ray/springbootboard/controller/PostControllerTest.java
Labels: 🔥 매운맛, Team-Ray

#231 [4기 김혜민] Spring Boot JPA 게시판 구현 미션 제출합니다.
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/programmers/springbootboardjpa/SpringbootBoardJpaApplication.java
  src/main/java/com/programmers/springbootboardjpa/domain/BaseEntity.java
  src/main/java/com/programmers/springbootboardjpa/domain/post/controller/PostController.java
  src/main/java/com/programmers/springbootboardjpa/domain/post/domain/Post.java
  src/main/java/com/programmers/springbootboardjpa/domain/post/domain/PostRepository.java
  src/main/java/com/programmers/springbootboardjpa/domain/post/dto/PostCreateRequestDto.java
  src/main/java/com/programmers/springbootboardjpa/domain/post/dto/PostResponseDto.java
  src/main/java/com/programmers/springbootboardjpa/domain/post/dto/PostUpdateRequestDto.java
  src/main/java/com/programmers/springbootboardjpa/domain/post/service/PostService.java
  src/main/java/com/programmers/springbootboardjpa/domain/user/controller/UserController.java
  src/main/java/com/programmers/springbootboardjpa/domain/user/domain/User.java
  src/main/java/com/programmers/springbootboardjpa/domain/user/domain/UserRepository.java
  src/main/java/com/programmers/springbootboardjpa/domain/user/dto/UserRequestDto.java
  src/main/java/com/programmers/springbootboardjpa/domain/user/dto/UserResponseDto.java
  src/main/java/com/programmers/springbootboardjpa/domain/user/service/UserService.java
  src/main/java/com/programmers/springbootboardjpa/global/config/AuditConfig.java
  src/main/java/com/programmers/springbootboardjpa/global/config/JpaConfig.java
  src/main/java/com/programmers/springbootboardjpa/global/error/ErrorCode.java
  src/main/java/com/programmers/springbootboardjpa/global/error/ErrorResponse.java
  src/main/java/com/programmers/springbootboardjpa/global/error/GlobalExceptionHandler.java
  src/main/java/com/programmers/springbootboardjpa/global/error/exception/InvalidEntityValueException.java
  src/main/java/com/programmers/springbootboardjpa/global/error/exception/NotFoundException.java
  src/main/resources/application.yml
  src/test/java/com/programmers/springbootboardjpa/SpringbootBoardJpaApplicationTests.java
  src/test/java/com/programmers/springbootboardjpa/domain/post/controller/PostControllerTest.java
  src/test/java/com/programmers/springbootboardjpa/domain/post/service/PostServiceMockingTest.java
  src/test/java/com/programmers/springbootboardjpa/domain/post/service/PostServiceTest.java
  src/test/java/com/programmers/springbootboardjpa/domain/user/controller/UserControllerTest.java
  src/test/java/com/programmers/springbootboardjpa/domain/user/service/UserServiceMockingTest.java
  src/test/java/com/programmers/springbootboardjpa/domain/user/service/UserServiceTest.java
Labels: 🔥 매운맛, Team-F

#264 [4기 김범우, 최성원] - 컨트롤러 테스트 코드 작성, restdocs 문서화
  build.gradle
  src/main/java/com/kdt/board/domain/post/service/PostService.java
  src/main/java/com/kdt/board/domain/user/service/UserService.java
  src/main/java/com/kdt/board/global/exception/BaseException.java
  src/test/java/com/kdt/board/domain/post/controller/PostControllerTest.java
Labels: 🔥 매운맛, Team-Ray

#219 [4기 장수연] Spring Boot JPA 게시판 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/index.adoc
  src/main/java/com/jpaboard/JpaBoardApplication.java
  src/main/java/com/jpaboard/entity/BaseEntity.java
  src/main/java/com/jpaboard/exception/GlobalExceptionHandler.java
  src/main/java/com/jpaboard/exception/NotFoundPostException.java
  src/main/java/com/jpaboard/exception/NotFoundUserException.java
  src/main/java/com/jpaboard/post/application/PostService.java
  src/main/java/com/jpaboard/post/domain/Post.java
  src/main/java/com/jpaboard/post/infra/JpaPostRepository.java
  src/main/java/com/jpaboard/post/ui/PostCommon.java
  src/main/java/com/jpaboard/post/ui/PostCreate.java
  src/main/java/com/jpaboard/post/ui/PostRestController.java
  src/main/java/com/jpaboard/post/ui/PostUpdate.java
  src/main/java/com/jpaboard/post/ui/dto/PageParam.java
  src/main/java/com/jpaboard/user/application/UserService.java
  src/main/java/com/jpaboard/user/domain/User.java
  src/main/java/com/jpaboard/user/infra/JpaUserRepository.java
  src/main/java/com/jpaboard/user/ui/UserController.java
  src/main/java/com/jpaboard/user/ui/UserConverter.java
  src/main/java/com/jpaboard/user/ui/dto/UserDto.java
  src/main/resources/application.yml
  src/test/java/com/jpaboard/JpaBoardApplicationTests.java
  src/test/java/com/jpaboard/domain/PostValidateTest.java
  src/test/java/com/jpaboard/domain/UserValidateTest.java
  src/test/java/com/jpaboard/ui/PostControllerTest.java
Labels: 💧 순한맛, Team-Kyu

#218 [4기 신범철] Spring Boot JPA 게시판 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  docs/v1/img.png
  docs/v1/img_1.png
  docs/v1/img_2.png
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/docs/index.adoc
  src/main/docs/index.html
  src/main/java/com/programmers/jpa_board/JpaBoardApplication.java
  src/main/java/com/programmers/jpa_board/global/ApiResponse.java
  src/main/java/com/programmers/jpa_board/global/BaseEntity.java
  src/main/java/com/programmers/jpa_board/global/exception/ExceptionMessage.java
  src/main/java/com/programmers/jpa_board/global/exception/GlobalExceptionHandler.java
  src/main/java/com/programmers/jpa_board/global/exception/NotFoundException.java
  src/main/java/com/programmers/jpa_board/post/application/PostService.java
  src/main/java/com/programmers/jpa_board/post/application/PostServiceImpl.java
  src/main/java/com/programmers/jpa_board/post/domain/Post.java
  src/main/java/com/programmers/jpa_board/post/domain/dto/CommonResponse.java
  src/main/java/com/programmers/jpa_board/post/domain/dto/CreatePostRequest.java
  src/main/java/com/programmers/jpa_board/post/domain/dto/PostDto.java
  src/main/java/com/programmers/jpa_board/post/domain/dto/UpdatePostRequest.java
  src/main/java/com/programmers/jpa_board/post/infra/PostRepository.java
  src/main/java/com/programmers/jpa_board/post/ui/PostController.java
  src/main/java/com/programmers/jpa_board/post/util/PostConverter.java
  src/main/java/com/programmers/jpa_board/user/application/UserProviderService.java
  src/main/java/com/programmers/jpa_board/user/application/UserServiceImpl.java
  src/main/java/com/programmers/jpa_board/user/domain/User.java
  src/main/java/com/programmers/jpa_board/user/domain/dto/CreateUserRequest.java
  src/main/java/com/programmers/jpa_board/user/domain/dto/UserDto.java
  src/main/java/com/programmers/jpa_board/user/domain/dto/UserResponse.java
  src/main/java/com/programmers/jpa_board/user/infra/UserRepository.java
  src/main/java/com/programmers/jpa_board/user/ui/UserController.java
  src/main/java/com/programmers/jpa_board/user/util/UserConverter.java
  src/main/resources/application.yaml
  src/test/java/com/programmers/jpa_board/post/domain/PostDomainTest.java
  src/test/java/com/programmers/jpa_board/post/ui/PostRestDocsTest.java
  src/test/java/com/programmers/jpa_board/user/domain/UserDomainTest.java
  src/test/java/com/programmers/jpa_board/user/domain/UserRestDocsTest.java
Labels: 🔥 매운맛, Team-Kyu

#248 [4기 이근우] Spring Boot JPA로 게시판 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/springbootboardjpa/SpringbootBoardJpaApplication.java
  src/main/java/com/springbootboardjpa/common/BaseEntity.java
  src/main/java/com/springbootboardjpa/common/NoSuchEntityException.java
  src/main/java/com/springbootboardjpa/global/JpaConfig.java
  src/main/java/com/springbootboardjpa/member/domain/Member.java
  src/main/java/com/springbootboardjpa/member/domain/MemberRepository.java
  src/main/java/com/springbootboardjpa/member/domain/Name.java
  src/main/java/com/springbootboardjpa/member/exception/InValidMemberException.java
  src/main/java/com/springbootboardjpa/post/application/PostService.java
  src/main/java/com/springbootboardjpa/post/domain/Content.java
  src/main/java/com/springbootboardjpa/post/domain/Post.java
  src/main/java/com/springbootboardjpa/post/domain/PostRepository.java
  src/main/java/com/springbootboardjpa/post/dto/PostRequest.java
  src/main/java/com/springbootboardjpa/post/dto/PostResponse.java
  src/main/java/com/springbootboardjpa/post/dto/PostWithoutContentResponse.java
  src/main/java/com/springbootboardjpa/post/dto/PostsResponse.java
  src/main/java/com/springbootboardjpa/post/presentation/PostController.java
  src/main/java/com/springbootboardjpa/post/presentation/PostExceptionController.java
  src/test/java/com/springbootboardjpa/SpringbootBoardJpaApplicationTests.java
  src/test/java/com/springbootboardjpa/global/TestConfig.java
  src/test/java/com/springbootboardjpa/member/domain/NameTest.java
  src/test/java/com/springbootboardjpa/post/application/PostServiceTest.java
  src/test/java/com/springbootboardjpa/post/domain/PostRepositoryTest.java
  src/test/java/com/springbootboardjpa/post/presentation/PostControllerTest.java
Labels: 🔥 매운맛, Team-F

#251 [4기 민승현] Spring Boot JPA 게시판 구현 미션 제출합니다.
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/board/BoardApplication.java
  src/main/java/com/example/board/config/JpaAuditingConfig.java
  src/main/java/com/example/board/contant/LikeStatus.java
  src/main/java/com/example/board/controller/CommentController.java
  src/main/java/com/example/board/controller/LikeController.java
  src/main/java/com/example/board/controller/PostController.java
  src/main/java/com/example/board/controller/UserController.java
  src/main/java/com/example/board/domain/BaseTime.java
  src/main/java/com/example/board/domain/entity/Comment.java
  src/main/java/com/example/board/domain/entity/CommentLike.java
  src/main/java/com/example/board/domain/entity/Like.java
  src/main/java/com/example/board/domain/entity/Post.java
  src/main/java/com/example/board/domain/entity/PostLike.java
  src/main/java/com/example/board/domain/entity/User.java
  src/main/java/com/example/board/domain/entity/repository/CommentRepository.java
  src/main/java/com/example/board/domain/entity/repository/LikeRepository.java
  src/main/java/com/example/board/domain/entity/repository/PostRepository.java
  src/main/java/com/example/board/domain/entity/repository/UserRepository.java
  src/main/java/com/example/board/domain/service/CommentService.java
  src/main/java/com/example/board/domain/service/LikeService.java
  src/main/java/com/example/board/domain/service/PostService.java
  src/main/java/com/example/board/domain/service/UserService.java
  src/main/java/com/example/board/dto/comment/CommentRequestDto.java
  src/main/java/com/example/board/dto/comment/CommentResponseDto.java
  src/main/java/com/example/board/dto/like/LikePostRequestDto.java
  src/main/java/com/example/board/dto/post/PostRequestDto.java
  src/main/java/com/example/board/dto/post/PostResponseDto.java
  src/main/java/com/example/board/dto/post/PostWithCommentResponseDto.java
  src/main/java/com/example/board/dto/user/UserResponseDto.java
  src/main/java/com/example/board/dto/user/UserSaveRequestDto.java
  src/main/java/com/example/board/dto/user/UserUpdateRequestDto.java
  src/main/java/com/example/board/exception/ErrorMessage.java
  src/main/java/com/example/board/exception/comment/CommentExceptionHandler.java
  src/main/java/com/example/board/exception/comment/NotFoundCommentException.java
  src/main/java/com/example/board/exception/post/NotFoundPostException.java
  src/main/java/com/example/board/exception/post/PostAccessDeniedException.java
  src/main/java/com/example/board/exception/post/PostExceptionHandler.java
  src/main/java/com/example/board/exception/user/NotFoundUserException.java
  src/main/java/com/example/board/exception/user/UserExceptionHandler.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/com/example/board/BoardApplicationTests.java
Labels: 🔥 매운맛, Team-Navy

#244 [4기 배준일] Spring Boot JPA 게시판 구현 미션 제출합니다.
  board/.gitignore
  board/build.gradle
  board/gradle/wrapper/gradle-wrapper.jar
  board/gradle/wrapper/gradle-wrapper.properties
  board/gradlew
  board/gradlew.bat
  board/settings.gradle
  board/src/docs/index.adoc
  board/src/main/java/com/example/board/BoardApplication.java
  board/src/main/java/com/example/board/domain/post/Post.java
  board/src/main/java/com/example/board/domain/post/controller/PostController.java
  board/src/main/java/com/example/board/domain/post/dto/PostCreateRequest.java
  board/src/main/java/com/example/board/domain/post/dto/PostResponse.java
  board/src/main/java/com/example/board/domain/post/dto/PostUpdateRequest.java
  board/src/main/java/com/example/board/domain/post/repository/PostRepository.java
  board/src/main/java/com/example/board/domain/post/service/PostService.java
  board/src/main/java/com/example/board/domain/user/User.java
  board/src/main/java/com/example/board/domain/user/dto/UserCreateRequest.java
  board/src/main/java/com/example/board/domain/user/dto/UserResponse.java
  board/src/main/java/com/example/board/domain/user/repository/UserRepository.java
  board/src/main/java/com/example/board/domain/user/service/UserService.java
  board/src/main/java/com/example/board/global/AuditConfig.java
  board/src/main/java/com/example/board/global/BaseEntity.java
  board/src/main/resources/application.yml
  board/src/test/java/com/example/board/BoardApplicationTests.java
  board/src/test/java/com/example/board/domain/post/controller/PostControllerTest.java
  board/src/test/java/com/example/board/domain/post/repository/PostRepositoryTest.java
  board/src/test/java/com/example/board/domain/post/service/PostServiceTest.java
Labels: 🔥 매운맛, Team-Navy
